import assert from 'node:assert/strict'
import {
  chmod,
  cp,
  lstat,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  symlink,
  utimes,
  writeFile,
} from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'

import { generateTypedSql } from '../src/generator.js'

const fixtureRoot = new URL('./fixtures/', import.meta.url)
const generatedMarker = '// This file is auto-generated by postgres-typed-sql'

async function copyFixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'postgres-typed-sql-output-'))
  await cp(fixtureRoot, root, { recursive: true })
  return root
}

function generate(root: string, include: readonly string[] = ['queries']) {
  return generateTypedSql({
    include,
    rootDir: root,
    scalarProfile: 'node-postgres',
    schema: 'schema.sql',
  })
}

test('analysis failure leaves every existing output and stale file untouched', async () => {
  const root = await copyFixture()
  await generate(root)

  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const queryPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const stalePath = join(root, 'queries/stale.typed-sql.ts')
  const catalogBefore = await readFile(catalogPath, 'utf8')
  const queryBefore = await readFile(queryPath, 'utf8')
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)

  const schemaPath = join(root, 'schema.sql')
  await writeFile(schemaPath, `${await readFile(schemaPath, 'utf8')}\ncreate type public.new_status as enum ('new');\n`)
  await writeFile(join(root, 'queries/invalid.typed.sql'), 'select missing_column from public.accounts\n')

  await assert.rejects(generate(root), /column "missing_column" does not exist/u)
  assert.equal(await readFile(catalogPath, 'utf8'), catalogBefore)
  assert.equal(await readFile(queryPath, 'utf8'), queryBefore)
  assert.equal(await readFile(stalePath, 'utf8'), `${generatedMarker}\nexport const stale = true\n`)
})

test('unchanged generation preserves output modification times', async () => {
  const root = await copyFixture()
  await generate(root)

  const outputPaths = [
    join(root, 'postgres-typed-sql.types.ts'),
    join(root, 'queries/find-account-by-email.typed-sql.ts'),
  ]
  const oldTimestamp = new Date('2001-02-03T04:05:06.000Z')
  for (const outputPath of outputPaths) {
    await utimes(outputPath, oldTimestamp, oldTimestamp)
  }
  const before = await Promise.all(outputPaths.map(async (outputPath) => (await stat(outputPath)).mtimeMs))

  await generate(root)
  const after = await Promise.all(outputPaths.map(async (outputPath) => (await stat(outputPath)).mtimeMs))
  assert.deepEqual(after, before)
})

test('stale cleanup deduplicates overlapping roots and requires a leading marker', async () => {
  const root = await copyFixture()
  const stalePath = join(root, 'queries/stale.typed-sql.ts')
  const protectedPath = join(root, 'queries/protected.typed-sql.ts')
  const spoofedPrefixPath = join(root, 'queries/spoofed-prefix.typed-sql.ts')
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)
  await writeFile(protectedPath, `export const handwritten = true\n${generatedMarker}\n`)
  await writeFile(spoofedPrefixPath, `${generatedMarker} copied into a handwritten file\n`)

  const result = await generate(root, ['.', 'queries'])
  assert.equal(result.removedFiles, 1)
  await assert.rejects(
    readFile(stalePath, 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
  assert.equal(await readFile(protectedPath, 'utf8'), `export const handwritten = true\n${generatedMarker}\n`)
  assert.equal(await readFile(spoofedPrefixPath, 'utf8'), `${generatedMarker} copied into a handwritten file\n`)
})

test('stale cleanup preserves a catalog output located under an include root', async () => {
  const root = await copyFixture()
  const catalogPath = join(root, 'queries/catalog.typed-sql.ts')
  const result = await generateTypedSql({
    include: ['queries'],
    rootDir: root,
    scalarProfile: 'node-postgres',
    schema: 'schema.sql',
    typesOutput: catalogPath,
  })

  assert.equal(result.removedFiles, 0)
  assert.match(await readFile(catalogPath, 'utf8'), /export interface CatalogDb/u)
})

test('staging failure cannot partially replace other valid outputs', async () => {
  const root = await copyFixture()
  await generate(root)

  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const firstQueryPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const blockedQueryPath = join(root, 'queries/list-accounts-with-posts.typed-sql.ts')
  const catalogBefore = await readFile(catalogPath, 'utf8')
  const firstQueryBefore = await readFile(firstQueryPath, 'utf8')

  const schemaPath = join(root, 'schema.sql')
  await writeFile(
    schemaPath,
    `${await readFile(schemaPath, 'utf8')}\ncreate type public.pending_state as enum ('pending');\n`
  )
  const firstSourcePath = join(root, 'queries/find-account-by-email.typed.sql')
  await writeFile(firstSourcePath, `${await readFile(firstSourcePath, 'utf8')}\n`)
  await rm(blockedQueryPath)
  await mkdir(blockedQueryPath)

  await assert.rejects(generate(root))
  assert.equal(await readFile(catalogPath, 'utf8'), catalogBefore)
  assert.equal(await readFile(firstQueryPath, 'utf8'), firstQueryBefore)

  const stagingArtifacts = [...(await readdir(root)), ...(await readdir(join(root, 'queries')))].filter(
    (entry) => entry.endsWith('.staged') || entry.endsWith('.backup')
  )
  assert.deepEqual(stagingArtifacts, [])
})

test('stale deletion failure rolls back every generated output', async () => {
  const root = await copyFixture()
  await generate(root)

  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const queryPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const catalogBefore = await readFile(catalogPath, 'utf8')
  const queryBefore = await readFile(queryPath, 'utf8')
  const lockedDirectory = join(root, 'queries/locked')
  const stalePath = join(lockedDirectory, 'stale.typed-sql.ts')
  await mkdir(lockedDirectory)
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)

  const schemaPath = join(root, 'schema.sql')
  await writeFile(
    schemaPath,
    `${await readFile(schemaPath, 'utf8')}\ncreate type public.pending_state as enum ('pending');\n`
  )
  const sourcePath = join(root, 'queries/find-account-by-email.typed.sql')
  await writeFile(sourcePath, `${await readFile(sourcePath, 'utf8')}\n`)
  await chmod(lockedDirectory, 0o555)
  try {
    await assert.rejects(generate(root), /EACCES|operation not permitted|permission denied/iu)
  } finally {
    await chmod(lockedDirectory, 0o755)
  }

  assert.equal(await readFile(catalogPath, 'utf8'), catalogBefore)
  assert.equal(await readFile(queryPath, 'utf8'), queryBefore)
  assert.equal(await readFile(stalePath, 'utf8'), `${generatedMarker}\nexport const stale = true\n`)
})

test('catalog and statement outputs cannot claim the same destination', async () => {
  const root = await copyFixture()
  const conflictingPath = join(root, 'queries/find-account-by-email.typed-sql.ts')

  await assert.rejects(
    generateTypedSql({
      include: ['queries'],
      rootDir: root,
      scalarProfile: 'node-postgres',
      schema: 'schema.sql',
      typesOutput: conflictingPath,
    }),
    /is claimed more than once/u
  )
  await assert.rejects(
    readFile(conflictingPath, 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
})

test('uses canonical destination identity through symlinked parent directories', async () => {
  const root = await copyFixture()
  await symlink(join(root, 'queries'), join(root, 'query-link'))
  const config = {
    include: ['queries', 'query-link'],
    rootDir: root,
    scalarProfile: 'node-postgres' as const,
    schema: 'schema.sql',
    typesOutput: 'query-link/catalog.typed-sql.ts',
  }

  const first = await generateTypedSql(config)
  assert.equal(first.statementCount, 4)
  const stalePath = join(root, 'queries/stale.typed-sql.ts')
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)
  const second = await generateTypedSql(config)
  assert.equal(second.statementCount, 4)
  assert.equal(second.removedFiles, 1)
  await assert.rejects(readFile(stalePath, 'utf8'), /ENOENT/u)
  const third = await generateTypedSql(config)
  assert.equal(third.removedFiles, 0)
  assert.match(await readFile(join(root, 'queries/catalog.typed-sql.ts'), 'utf8'), /generated by postgres-typed-sql/u)

  const collisionRoot = await copyFixture()
  await symlink(join(collisionRoot, 'queries'), join(collisionRoot, 'query-link'))
  await assert.rejects(
    generateTypedSql({
      include: ['queries'],
      rootDir: collisionRoot,
      scalarProfile: 'node-postgres',
      schema: 'schema.sql',
      typesOutput: 'query-link/find-account-by-email.typed-sql.ts',
    }),
    /same filesystem destination.*claimed more than once/u
  )
})

test('uses the destination filesystem rather than the host platform for case identity', async () => {
  const root = await copyFixture()
  const probe = join(root, 'CaseProbe')
  await writeFile(probe, 'probe')
  let caseSensitive = false
  try {
    await readFile(join(root, 'caseprobe'), 'utf8')
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') {
      caseSensitive = true
    } else {
      throw error
    }
  }

  const generation = generateTypedSql({
    include: ['queries'],
    rootDir: root,
    scalarProfile: 'node-postgres',
    schema: 'schema.sql',
    typesOutput: 'queries/FIND-ACCOUNT-BY-EMAIL.typed-sql.ts',
  })
  if (caseSensitive) {
    await generation
    assert.match(
      await readFile(join(root, 'queries/FIND-ACCOUNT-BY-EMAIL.typed-sql.ts'), 'utf8'),
      /export interface CatalogDb/u
    )
    assert.match(
      await readFile(join(root, 'queries/find-account-by-email.typed-sql.ts'), 'utf8'),
      /createTypedSqlStatement/u
    )
  } else {
    await assert.rejects(generation, /same filesystem destination.*claimed more than once/u)
  }
})

test('catalog output symlinks are rejected before any generated output is mutated', async () => {
  const root = await copyFixture()
  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const catalogTargetPath = join(root, 'catalog-target.ts')
  const targetContents = 'export const catalogTarget = true\n'
  await writeFile(catalogTargetPath, targetContents)
  await symlink(catalogTargetPath, catalogPath)

  await assert.rejects(
    generate(root),
    /Generated output path .*postgres-typed-sql\.types\.ts must not be a symbolic link/u
  )
  assert.equal((await lstat(catalogPath)).isSymbolicLink(), true)
  assert.equal(await readFile(catalogTargetPath, 'utf8'), targetContents)
  await assert.rejects(
    readFile(join(root, 'queries/find-account-by-email.typed-sql.ts'), 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
})

test('statement output symlinks are rejected before catalog or sibling outputs are mutated', async () => {
  const root = await copyFixture()
  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const catalogContents = 'export const existingCatalog = true\n'
  const statementPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const statementTargetPath = join(root, 'statement-target.ts')
  const targetContents = 'export const statementTarget = true\n'
  await writeFile(catalogPath, catalogContents)
  await writeFile(statementTargetPath, targetContents)
  await symlink(statementTargetPath, statementPath)

  await assert.rejects(
    generate(root),
    /Generated output path .*find-account-by-email\.typed-sql\.ts must not be a symbolic link/u
  )
  assert.equal(await readFile(catalogPath, 'utf8'), catalogContents)
  assert.equal((await lstat(statementPath)).isSymbolicLink(), true)
  assert.equal(await readFile(statementTargetPath, 'utf8'), targetContents)
  await assert.rejects(
    readFile(join(root, 'queries/list-accounts-with-posts.typed-sql.ts'), 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
  const stagingArtifacts = [...(await readdir(root)), ...(await readdir(join(root, 'queries')))].filter(
    (entry) => entry.endsWith('.staged') || entry.endsWith('.backup')
  )
  assert.deepEqual(stagingArtifacts, [])
})
