import assert from 'node:assert/strict'
import { cp, mkdir, mkdtemp, readFile, readdir, rm, stat, utimes, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'

import { generateTypedSql } from '../src/generator.js'

const fixtureRoot = new URL('./fixtures/', import.meta.url)
const generatedMarker = '// This file is auto-generated by postgres-typed-sql'

async function copyFixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'postgres-typed-sql-output-'))
  await cp(fixtureRoot, root, { recursive: true })
  return root
}

function generate(root: string, include: readonly string[] = ['queries']) {
  return generateTypedSql({
    include,
    rootDir: root,
    scalarProfile: 'node-postgres',
    schema: 'schema.sql',
  })
}

test('analysis failure leaves every existing output and stale file untouched', async () => {
  const root = await copyFixture()
  await generate(root)

  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const queryPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const stalePath = join(root, 'queries/stale.typed-sql.ts')
  const catalogBefore = await readFile(catalogPath, 'utf8')
  const queryBefore = await readFile(queryPath, 'utf8')
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)

  const schemaPath = join(root, 'schema.sql')
  await writeFile(schemaPath, `${await readFile(schemaPath, 'utf8')}\ncreate type public.new_status as enum ('new');\n`)
  await writeFile(join(root, 'queries/invalid.typed.sql'), 'select missing_column from public.accounts\n')

  await assert.rejects(generate(root), /column "missing_column" does not exist/u)
  assert.equal(await readFile(catalogPath, 'utf8'), catalogBefore)
  assert.equal(await readFile(queryPath, 'utf8'), queryBefore)
  assert.equal(await readFile(stalePath, 'utf8'), `${generatedMarker}\nexport const stale = true\n`)
})

test('unchanged generation preserves output modification times', async () => {
  const root = await copyFixture()
  await generate(root)

  const outputPaths = [
    join(root, 'postgres-typed-sql.types.ts'),
    join(root, 'queries/find-account-by-email.typed-sql.ts'),
  ]
  const oldTimestamp = new Date('2001-02-03T04:05:06.000Z')
  for (const outputPath of outputPaths) {
    await utimes(outputPath, oldTimestamp, oldTimestamp)
  }
  const before = await Promise.all(outputPaths.map(async (outputPath) => (await stat(outputPath)).mtimeMs))

  await generate(root)
  const after = await Promise.all(outputPaths.map(async (outputPath) => (await stat(outputPath)).mtimeMs))
  assert.deepEqual(after, before)
})

test('stale cleanup deduplicates overlapping roots and requires a leading marker', async () => {
  const root = await copyFixture()
  const stalePath = join(root, 'queries/stale.typed-sql.ts')
  const protectedPath = join(root, 'queries/protected.typed-sql.ts')
  const spoofedPrefixPath = join(root, 'queries/spoofed-prefix.typed-sql.ts')
  await writeFile(stalePath, `${generatedMarker}\nexport const stale = true\n`)
  await writeFile(protectedPath, `export const handwritten = true\n${generatedMarker}\n`)
  await writeFile(spoofedPrefixPath, `${generatedMarker} copied into a handwritten file\n`)

  const result = await generate(root, ['.', 'queries'])
  assert.equal(result.removedFiles, 1)
  await assert.rejects(
    readFile(stalePath, 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
  assert.equal(await readFile(protectedPath, 'utf8'), `export const handwritten = true\n${generatedMarker}\n`)
  assert.equal(await readFile(spoofedPrefixPath, 'utf8'), `${generatedMarker} copied into a handwritten file\n`)
})

test('staging failure cannot partially replace other valid outputs', async () => {
  const root = await copyFixture()
  await generate(root)

  const catalogPath = join(root, 'postgres-typed-sql.types.ts')
  const firstQueryPath = join(root, 'queries/find-account-by-email.typed-sql.ts')
  const blockedQueryPath = join(root, 'queries/list-accounts-with-posts.typed-sql.ts')
  const catalogBefore = await readFile(catalogPath, 'utf8')
  const firstQueryBefore = await readFile(firstQueryPath, 'utf8')

  const schemaPath = join(root, 'schema.sql')
  await writeFile(
    schemaPath,
    `${await readFile(schemaPath, 'utf8')}\ncreate type public.pending_state as enum ('pending');\n`
  )
  const firstSourcePath = join(root, 'queries/find-account-by-email.typed.sql')
  await writeFile(firstSourcePath, `${await readFile(firstSourcePath, 'utf8')}\n`)
  await rm(blockedQueryPath)
  await mkdir(blockedQueryPath)

  await assert.rejects(generate(root))
  assert.equal(await readFile(catalogPath, 'utf8'), catalogBefore)
  assert.equal(await readFile(firstQueryPath, 'utf8'), firstQueryBefore)

  const stagingArtifacts = [...(await readdir(root)), ...(await readdir(join(root, 'queries')))].filter(
    (entry) => entry.endsWith('.staged') || entry.endsWith('.backup')
  )
  assert.deepEqual(stagingArtifacts, [])
})

test('catalog and statement outputs cannot claim the same destination', async () => {
  const root = await copyFixture()
  const conflictingPath = join(root, 'queries/find-account-by-email.typed-sql.ts')

  await assert.rejects(
    generateTypedSql({
      include: ['queries'],
      rootDir: root,
      scalarProfile: 'node-postgres',
      schema: 'schema.sql',
      typesOutput: conflictingPath,
    }),
    /is claimed more than once/u
  )
  await assert.rejects(
    readFile(conflictingPath, 'utf8'),
    (error: unknown) => error instanceof Error && 'code' in error && error.code === 'ENOENT'
  )
})
