import { readFileSync } from 'node:fs'
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'

import {
  buildTypedSqlPostgresIrFromCompiledConfigs,
  type TypedSqlPostgresIrColumnSource,
  type TypedSqlPostgresIrJsonShape,
  type TypedSqlPostgresIrRowBounds,
  type TypedSqlPostgresIrRowCardinality,
} from './analyzer-ir.js'
import { generateCatalogTypes } from './catalog-generator.js'
import type { ResolvedPostgresTypedSqlConfig } from './config.js'
import { resolveConfig, type PostgresTypedSqlConfig } from './config.js'
import type { PostgresQueryable } from './database.js'
import { createAnalysisDatabase } from './engine.js'

let activeConfig: ResolvedPostgresTypedSqlConfig | undefined
let generationInProgress = false

function currentConfig(): ResolvedPostgresTypedSqlConfig {
  if (!activeConfig) {
    throw new Error('Postgres Typed SQL generator context is unavailable.')
  }
  return activeConfig
}
const typedSqlSourceSuffix = '.typed.sql'
const typedSqlOutputSuffix = '.typed-sql.ts'
const legacyTypedSqlOutputSuffixes = ['.typed.sql.ts']
const generatedByMarker = 'This file is auto-generated by @fli/postgres-typed-sql'
const ignoredDiscoveryDirectories = new Set([
  '.git',
  '.next',
  '.turbo',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'out',
  'playwright-report',
  'reports',
  'test-results',
])

interface SqlParameter {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
  readonly propertyName: string
  readonly tsType?: string
}

interface SqlColumn {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
  readonly propertyName: string
  readonly tsType?: string
}

interface TypedSqlConfig {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameter[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface CompiledTypedSql {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameter[]
  readonly parameterNames: readonly string[]
  readonly parameterTypes: readonly (string | undefined)[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface ResolvedSqlParameter {
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly tsType: string
}

interface ResolvedSqlColumn {
  readonly jsonShape?: TypedSqlPostgresIrJsonShape
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly source: TypedSqlPostgresIrColumnSource | null
  readonly tsType: string
}

type TypedSqlCommand = 'delete' | 'insert' | 'merge' | 'select' | 'unknown' | 'update'
type TypedSqlAccess = 'read' | 'write'

interface ResolvedTypedSql {
  readonly access: TypedSqlAccess
  readonly cardinality: TypedSqlPostgresIrRowCardinality
  readonly columns: readonly ResolvedSqlColumn[]
  readonly command: TypedSqlCommand
  readonly generatedTypeDeclarations: readonly string[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly ResolvedSqlParameter[]
  readonly parameterNames: readonly string[]
  readonly parameterTypes: readonly string[]
  readonly rowBounds: TypedSqlPostgresIrRowBounds
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

const pgTypeToTsType = new Map<string, string>([
  ['bigint', 'PgInt8String'],
  ['bit', 'string'],
  ['bit varying', 'string'],
  ['boolean', 'boolean'],
  ['box', 'string'],
  ['bytea', 'PgByteaHexString'],
  ['char', 'string'],
  ['cidr', 'string'],
  ['circle', 'string'],
  ['date', 'PgDateString'],
  ['double precision', 'PgFloat8String'],
  ['inet', 'string'],
  ['integer', 'PgInt4String'],
  ['interval', 'PgIntervalString'],
  ['line', 'string'],
  ['lseg', 'string'],
  ['macaddr', 'string'],
  ['macaddr8', 'string'],
  ['money', 'string'],
  ['name', 'string'],
  ['json', 'DbJsonSelected'],
  ['jsonb', 'DbJsonSelected'],
  ['numeric', 'PgNumericString'],
  ['oid', 'PgOidString'],
  ['path', 'string'],
  ['pg_lsn', 'string'],
  ['point', 'string'],
  ['polygon', 'string'],
  ['real', 'PgFloat4String'],
  ['smallint', 'PgInt2String'],
  ['text', 'string'],
  ['time without time zone', 'PgTimeString'],
  ['time with time zone', 'PgTimetzString'],
  ['timestamp without time zone', 'PgTimestampString'],
  ['timestamp with time zone', 'PgTimestamptzString'],
  ['timestamptz', 'PgTimestamptzString'],
  ['tsquery', 'string'],
  ['tsvector', 'string'],
  ['unknown', 'unknown'],
  ['uuid', 'PgUuidString'],
  ['void', 'unknown'],
  ['xml', 'string'],
])

for (const rangeType of ['daterange', 'int4range', 'int8range', 'numrange', 'tsrange', 'tstzrange']) {
  pgTypeToTsType.set(rangeType, 'string')
}

const dbScalarTypes = new Set(
  [
    ['DbJsonInput', 'db-scalars'],
    ['DbJsonSelected', 'db-scalars'],
    ['PgByteaHexString', 'db-scalars'],
    ['PgDateString', 'db-scalars'],
    ['PgFloat4String', 'db-scalars'],
    ['PgFloat8String', 'db-scalars'],
    ['PgInt2String', 'db-scalars'],
    ['PgInt4String', 'db-scalars'],
    ['PgInt8String', 'db-scalars'],
    ['PgIntervalString', 'db-scalars'],
    ['PgNumericString', 'db-scalars'],
    ['PgOidString', 'db-scalars'],
    ['PgTimestampString', 'db-scalars'],
    ['PgTimestamptzString', 'db-scalars'],
    ['PgTimeString', 'db-scalars'],
    ['PgTimetzString', 'db-scalars'],
    ['PgUuidString', 'db-scalars'],
  ].map(([type]) => type)
)

function camelCaseIdentifier(identifier: string): string {
  return identifier.replaceAll(/_([a-z0-9])/gu, (_match, letter: string) => letter.toUpperCase())
}

function pascalCaseIdentifier(identifier: string): string {
  const camelCase = camelCaseIdentifier(identifier)
  return `${camelCase.slice(0, 1).toUpperCase()}${camelCase.slice(1)}`
}

function requireSqlName(value: string, sourceFile: string): string {
  if (!/^[a-z][A-Za-z0-9]*$/u.test(value)) {
    throw new Error(`${sourceFile}: @name must be a lower camel-case identifier.`)
  }

  return value
}

function lowerCamelCaseFromPathBase(base: string): string {
  const parts = base.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0)
  if (parts.length === 0) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const [head, ...tail] = parts
  if (!head) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const identifier = [
    head.toLowerCase(),
    ...tail.map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`),
  ].join('')

  return requireSqlName(identifier, base)
}

function quotePropertyName(propertyName: string): string {
  return /^[A-Za-z_$][\w$]*$/u.test(propertyName) ? propertyName : JSON.stringify(propertyName)
}

function quoteString(value: string): string {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll('\t', '\\t')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')

  return value.includes("'") ? `"${escaped.replaceAll('"', '\\"')}"` : `'${escaped.replaceAll("'", "\\'")}'`
}

function relativePath(filePath: string): string {
  return relative(currentConfig().rootDir, filePath)
}

function normalizePgTypeName(pgType: string): string {
  if (pgType.startsWith('character varying') || pgType.startsWith('character(') || pgType === 'varchar') {
    return 'text'
  }
  if (pgType.startsWith('numeric(')) {
    return 'numeric'
  }
  if (pgType.startsWith('timestamp(') && pgType.endsWith(' without time zone')) {
    return 'timestamp without time zone'
  }
  if (pgType.startsWith('timestamp(') && pgType.endsWith(' with time zone')) {
    return 'timestamp with time zone'
  }
  if (pgType.startsWith('time(') && pgType.endsWith(' without time zone')) {
    return 'time without time zone'
  }
  if (pgType.startsWith('time(') && pgType.endsWith(' with time zone')) {
    return 'time with time zone'
  }
  return pgType
}

function postgresArrayElementType(pgType: string, typeName: string): string | null {
  const normalizedPgType = normalizePgTypeName(pgType)
  if (normalizedPgType.endsWith('[]')) {
    return normalizedPgType.slice(0, -2)
  }

  const normalizedTypeName = normalizePgTypeName(typeName)
  if (normalizedTypeName.startsWith('_') && normalizedTypeName.length > 1) {
    return normalizedTypeName.slice(1)
  }

  return null
}

function splitSchemaQualifiedPgType(pgType: string): { readonly schema: string; readonly typeName: string } | null {
  const match = /^([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)(\[\])?$/u.exec(pgType)
  if (!match?.[1] || !match[2]) {
    return null
  }

  return { schema: match[1], typeName: `${match[2]}${match[3] ?? ''}` }
}

function tsTypeForPgType(pgType: string, sourceFile: string, typeSchema = 'pg_catalog', typeName = ''): string {
  const schemaQualifiedType = typeSchema === 'pg_catalog' && !typeName ? splitSchemaQualifiedPgType(pgType) : null
  if (schemaQualifiedType) {
    return tsTypeForPgType(
      schemaQualifiedType.typeName,
      sourceFile,
      schemaQualifiedType.schema,
      schemaQualifiedType.typeName
    )
  }

  const arrayElementType = postgresArrayElementType(pgType, typeName)
  if (arrayElementType) {
    const elementType =
      typeSchema === 'pg_catalog'
        ? tsTypeForPgType(arrayElementType, sourceFile)
        : pascalCaseIdentifier(arrayElementType)
    return `readonly ${elementType}[]`
  }

  if (typeSchema !== 'pg_catalog') {
    return pascalCaseIdentifier(typeName || pgType)
  }

  const tsType = pgTypeToTsType.get(normalizePgTypeName(pgType))
  if (!tsType) {
    throw new Error(`${sourceFile}: no TypeScript mapping configured for PostgreSQL type ${pgType}.`)
  }

  return tsType
}

function parameterTsTypeForPgType(
  pgType: string,
  sourceFile: string,
  typeSchema = 'pg_catalog',
  typeName = ''
): string {
  const normalizedTypeName = normalizePgTypeName(typeName || pgType)
  if ((normalizedTypeName === 'json' || normalizedTypeName === 'jsonb') && typeSchema === 'pg_catalog') {
    return 'DbJsonInput'
  }

  return tsTypeForPgType(pgType, sourceFile, typeSchema, typeName)
}

function typedSqlCommandFromPostgres(command: string): TypedSqlCommand {
  switch (command.toLowerCase()) {
    case 'delete':
      return 'delete'
    case 'insert':
      return 'insert'
    case 'merge':
      return 'merge'
    case 'select':
      return 'select'
    case 'update':
      return 'update'
    default:
      return 'unknown'
  }
}

function typedSqlAccessForCommand(command: TypedSqlCommand): TypedSqlAccess {
  return command === 'select' ? 'read' : 'write'
}

function splitTopLevelSqlList(input: string): string[] {
  const values: string[] = []
  let current = ''
  let depth = 0
  let quote: '"' | "'" | null = null

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index]
    const next = input[index + 1]
    if (!char) {
      continue
    }

    if (quote) {
      current += char
      if (char === quote) {
        if (next === quote) {
          current += next
          index += 1
        } else {
          quote = null
        }
      }
      continue
    }

    if (char === "'" || char === '"') {
      quote = char
      current += char
      continue
    }

    if (char === '(') {
      depth += 1
      current += char
      continue
    }

    if (char === ')') {
      depth = Math.max(0, depth - 1)
      current += char
      continue
    }

    if (char === ',' && depth === 0) {
      values.push(current.trim())
      current = ''
      continue
    }

    current += char
  }

  const trimmed = current.trim()
  if (trimmed.length > 0) {
    values.push(trimmed)
  }
  return values
}

function parseQualifiedTableName(input: string): { readonly schema: string; readonly table: string } | null {
  const parts = input
    .trim()
    .replaceAll('"', '')
    .split('.')
    .filter((part) => part.length > 0)

  const table = parts.at(-1)
  if (!table) {
    return null
  }

  const schema = parts.length > 1 ? parts.at(-2) : undefined
  return {
    schema: schema ?? 'public',
    table,
  }
}

function normalizeColumnIdentifier(input: string): string | null {
  const column = input.trim().replaceAll('"', '').split('.').at(-1)

  return column && /^[A-Za-z_][A-Za-z0-9_]*$/u.test(column) ? column : null
}

function directParameterName(input: string, parameterNames: readonly string[]): string | null {
  const trimmed = input.trim()
  const namedMatch = /^\(?\s*:([A-Za-z_][A-Za-z0-9_]*)\s*(?:::[A-Za-z_][A-Za-z0-9_.]*)?\s*\)?$/u.exec(trimmed)
  if (namedMatch?.[1]) {
    return namedMatch[1]
  }

  const positionalMatch = /^\(?\s*\$(\d+)\s*(?:::[A-Za-z_][A-Za-z0-9_.]*)?\s*\)?$/u.exec(trimmed)
  if (!positionalMatch?.[1]) {
    return null
  }

  return parameterNames[Number(positionalMatch[1]) - 1] ?? null
}

function collectDmlParameterTargets(
  sql: string,
  parameterNames: readonly string[]
): {
  readonly column: string
  readonly parameter: string
  readonly table: string
}[] {
  const targets: {
    readonly column: string
    readonly parameter: string
    readonly table: string
  }[] = []

  const insertMatch =
    /\binsert\s+into\s+([A-Za-z_][A-Za-z0-9_".]*(?:\.[A-Za-z_][A-Za-z0-9_".]*)?)\s*\(([\s\S]*?)\)\s*values\s*\(([\s\S]*)\)\s*(?:on\s+conflict\b|returning\b|$)/iu.exec(
      sql
    )
  if (insertMatch?.[1] && insertMatch[2] && insertMatch[3]) {
    const tableName = parseQualifiedTableName(insertMatch[1])
    if (tableName) {
      const table = `${tableName.schema}.${tableName.table}`
      const columns = splitTopLevelSqlList(insertMatch[2]).map(normalizeColumnIdentifier)
      const values = splitTopLevelSqlList(insertMatch[3]).map((value) => directParameterName(value, parameterNames))
      for (const [index, column] of columns.entries()) {
        const parameter = values[index]
        if (column && parameter) {
          targets.push({ column, parameter, table })
        }
      }
    }
  }

  const updateMatch =
    /\bupdate\s+([A-Za-z_][A-Za-z0-9_".]*(?:\.[A-Za-z_][A-Za-z0-9_".]*)?)\s+set\s+([\s\S]*?)(?:\bwhere\b|$)/iu.exec(sql)
  if (updateMatch?.[1] && updateMatch[2]) {
    const tableName = parseQualifiedTableName(updateMatch[1])
    if (tableName) {
      const table = `${tableName.schema}.${tableName.table}`
      for (const assignment of splitTopLevelSqlList(updateMatch[2])) {
        const assignmentMatch = /^(.+?)\s*=\s*(.+)$/u.exec(assignment)
        if (!assignmentMatch?.[1] || !assignmentMatch[2]) {
          continue
        }
        const column = normalizeColumnIdentifier(assignmentMatch[1])
        const parameter = directParameterName(assignmentMatch[2], parameterNames)
        if (column && parameter) {
          targets.push({ column, parameter, table })
        }
      }
    }
  }

  return targets
}

function parseDirectiveLine(line: string): readonly string[] | null {
  const match = /^--\s*@(\w+)\s+(.+)$/u.exec(line)
  if (!match) {
    return null
  }

  const kind = match[1]
  const body = match[2]
  if (!kind || !body) {
    return null
  }

  return [kind, ...body.trim().split(/\s+/u)]
}

function parseDirectivePgType(pgType: string | undefined): {
  readonly nullable: boolean
  readonly pgType?: string
} {
  if (!pgType) {
    return { nullable: false }
  }

  if (pgType === '?') {
    return { nullable: true }
  }

  return pgType.endsWith('?') ? { nullable: true, pgType: pgType.slice(0, -1) } : { nullable: false, pgType }
}

async function walkTypedSqlFiles(directory: string, output: string[]): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true })
  for (const entry of entries) {
    const entryPath = join(directory, entry.name)
    if (entry.isDirectory()) {
      if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
        await walkTypedSqlFiles(entryPath, output)
      }
      continue
    }

    if (entry.isFile() && entry.name.endsWith(typedSqlSourceSuffix)) {
      output.push(entryPath)
    }
  }
}

async function findTypedSqlSourceFiles(): Promise<string[]> {
  const sourceFiles = new Set<string>()
  for (const includeRoot of currentConfig().include) {
    const entries: string[] = []
    await walkTypedSqlFiles(includeRoot, entries)
    for (const entry of entries) {
      sourceFiles.add(entry)
    }
  }
  return [...sourceFiles].toSorted((left, right) => relativePath(left).localeCompare(relativePath(right)))
}

function generatedOutputPath(sourcePath: string): string {
  return `${sourcePath.slice(0, -typedSqlSourceSuffix.length)}${typedSqlOutputSuffix}`
}

async function readTypedSqlConfigs(): Promise<TypedSqlConfig[]> {
  const sourcePaths = await findTypedSqlSourceFiles()
  const configs: TypedSqlConfig[] = []

  for (const sourcePath of sourcePaths) {
    const sourceFile = relativePath(sourcePath)
    const text = readFileSync(sourcePath, 'utf8')
    const lines = text.split(/\r?\n/u)
    const defaultName = lowerCamelCaseFromPathBase(basename(sourceFile, typedSqlSourceSuffix))
    let access: TypedSqlAccess | undefined
    let name = defaultName
    const parameters: SqlParameter[] = []
    const columns: SqlColumn[] = []
    const sqlLines: string[] = []

    for (const line of lines) {
      const directive = parseDirectiveLine(line)
      if (!directive) {
        sqlLines.push(line)
        continue
      }

      const kind = directive[0]
      const identifier = directive[1]
      const parsedPgType = parseDirectivePgType(directive[2])
      const pgType = parsedPgType.pgType
      if (kind === 'name') {
        if (!identifier) {
          throw new Error(`${sourceFile}: @name requires an identifier.`)
        }

        name = requireSqlName(identifier, sourceFile)
        continue
      }

      if (kind === 'access') {
        if (identifier !== 'read' && identifier !== 'write') {
          throw new Error(`${sourceFile}: @access requires read or write.`)
        }

        access = identifier
        continue
      }

      if (kind !== 'param' && kind !== 'column') {
        throw new Error(`${sourceFile}: unsupported typed SQL directive @${kind}.`)
      }

      if (!identifier) {
        throw new Error(`${sourceFile}: @${kind} requires a name.`)
      }

      const entry = {
        name: identifier,
        nullable: parsedPgType.nullable,
        pgType,
        propertyName: camelCaseIdentifier(identifier),
        tsType: pgType ? tsTypeForPgType(pgType, sourceFile) : undefined,
      }

      if (kind === 'param') {
        parameters.push(entry)
      } else {
        columns.push(entry)
      }
    }

    configs.push({
      access,
      columns,
      name,
      outputPath: generatedOutputPath(sourcePath),
      parameters,
      sourceFile,
      sourcePath,
      sql: sqlLines.join('\n').trim(),
    })
  }

  return configs
}

function assertUniqueTypedSqlNames(configs: readonly TypedSqlConfig[]): void {
  const firstSourceByName = new Map<string, string>()
  for (const config of configs) {
    const firstSource = firstSourceByName.get(config.name)
    if (firstSource) {
      throw new Error(`${config.sourceFile}: typed SQL statement name ${config.name} already used by ${firstSource}.`)
    }
    firstSourceByName.set(config.name, config.sourceFile)
  }
}

function compileTypedSql(config: TypedSqlConfig): CompiledTypedSql {
  const parametersByName = new Map(config.parameters.map((parameter) => [parameter.name, parameter]))
  const parameterNames: string[] = []
  const parameterTypes: (string | undefined)[] = []
  const placeholdersByName = new Map<string, number>()
  const parameters: SqlParameter[] = []
  const sql = config.sql.replaceAll(/(?<!:):([A-Za-z_][A-Za-z0-9_]*)/gu, (match, name: string) => {
    const existingIndex = placeholdersByName.get(name)
    if (existingIndex !== undefined) {
      return `$${existingIndex}`
    }

    const parameter =
      parametersByName.get(name) ??
      ({
        name,
        propertyName: camelCaseIdentifier(name),
      } satisfies SqlParameter)

    parameters.push(parameter)
    parameterNames.push(parameter.propertyName)
    parameterTypes.push(parameter.pgType)
    const placeholderIndex = parameterNames.length
    placeholdersByName.set(name, placeholderIndex)
    return `$${placeholderIndex}`
  })

  const unusedParameters = config.parameters.filter(
    (parameter) => !parameters.some((used) => used.name === parameter.name)
  )
  if (unusedParameters.length > 0) {
    throw new Error(
      `${config.sourceFile}: declared parameter(s) not used: ${unusedParameters.map((parameter) => parameter.name).join(', ')}.`
    )
  }

  return {
    access: config.access,
    columns: config.columns,
    name: config.name,
    outputPath: config.outputPath,
    parameters,
    parameterNames,
    parameterTypes,
    sourceFile: config.sourceFile,
    sourcePath: config.sourcePath,
    sql,
  }
}

interface GeneratedJsonTypeDeclaration {
  readonly fields: readonly {
    readonly nullable: boolean
    readonly propertyName: string
    readonly tsType: string
  }[]
  readonly name: string
}

function singularTypeName(name: string): string {
  return name.endsWith('Rows')
    ? name.slice(0, -1)
    : name.endsWith('ies')
      ? `${name.slice(0, -3)}y`
      : name.endsWith('ses')
        ? name.slice(0, -2)
        : name.endsWith('s') && name.length > 1
          ? name.slice(0, -1)
          : name
}

function scalarTsTypeForJsonShape(
  shape: Extract<TypedSqlPostgresIrJsonShape, { readonly kind: 'scalar' }>,
  sourceFile: string
): string {
  if (shape.tsType) {
    return shape.tsType
  }

  if (shape.pgType === 'unknown' || shape.pgTypeName === 'unknown' || shape.pgTypeSchema === 'unknown') {
    return 'DbJsonSelected'
  }

  return tsTypeForPgType(shape.pgType, sourceFile, shape.pgTypeSchema, shape.pgTypeName)
}

function tsTypeForJsonShape(
  shape: TypedSqlPostgresIrJsonShape,
  sourceFile: string,
  suggestedName: string,
  declarations: GeneratedJsonTypeDeclaration[],
  usedNames: Map<string, number>
): string {
  switch (shape.kind) {
    case 'array':
      return `readonly ${tsTypeForJsonShape(
        shape.element,
        sourceFile,
        singularTypeName(suggestedName),
        declarations,
        usedNames
      )}[]`
    case 'object': {
      const usedCount = usedNames.get(suggestedName) ?? 0
      usedNames.set(suggestedName, usedCount + 1)
      const name = usedCount === 0 ? suggestedName : `${suggestedName}${usedCount + 1}`
      declarations.push({
        fields: shape.fields.map((field) => ({
          nullable: field.shape.nullable,
          propertyName: camelCaseIdentifier(field.name),
          tsType: tsTypeForJsonShape(
            field.shape,
            sourceFile,
            `${name}${pascalCaseIdentifier(field.name)}`,
            declarations,
            usedNames
          ),
        })),
        name,
      })
      return name
    }
    case 'opaque':
      return 'DbJsonSelected'
    case 'scalar':
      return scalarTsTypeForJsonShape(shape, sourceFile)
  }
}

function collectReferencedTypes(source: string, output: Set<string>): void {
  for (const match of source.matchAll(/\b[A-Z][A-Za-z0-9_]*\b/gu)) {
    const [identifier] = match
    if (identifier) {
      output.add(identifier)
    }
  }
}

function moduleSpecifier(fromDirectory: string, targetPath: string): string {
  const withoutExtension = targetPath.replace(/\.tsx?$/u, '')
  const path = relative(fromDirectory, withoutExtension).replaceAll('\\', '/')
  return `${path.startsWith('.') ? path : `./${path}`}.js`
}

function renderImports(configs: readonly ResolvedTypedSql[]): string {
  const scalarImports = new Set<string>()
  const catalogTypeImports = new Set<string>()
  for (const config of configs) {
    const localTypeNames = new Set(
      config.generatedTypeDeclarations.flatMap((declaration) =>
        [...declaration.matchAll(/export (?:interface|type) ([A-Z][A-Za-z0-9_]*)/gu)].map((match) => match[1] ?? '')
      )
    )
    for (const entry of [...config.parameters, ...config.columns]) {
      const identifiers = new Set<string>()
      collectReferencedTypes(entry.tsType, identifiers)
      for (const identifier of identifiers) {
        if (localTypeNames.has(identifier)) {
          continue
        }
        if (dbScalarTypes.has(identifier)) {
          scalarImports.add(identifier)
        } else {
          catalogTypeImports.add(identifier)
        }
      }
    }
    for (const declaration of config.generatedTypeDeclarations) {
      const identifiers = new Set<string>()
      collectReferencedTypes(declaration, identifiers)
      for (const identifier of identifiers) {
        if (localTypeNames.has(identifier)) {
          continue
        }
        if (dbScalarTypes.has(identifier)) {
          scalarImports.add(identifier)
        } else if (!['Record'].includes(identifier)) {
          catalogTypeImports.add(identifier)
        }
      }
    }
  }

  const lines: string[] = []
  if (scalarImports.size > 0) {
    lines.push(
      `import type { ${[...scalarImports].toSorted().join(', ')} } from '${currentConfig().packageImport}/scalars'`
    )
  }
  if (catalogTypeImports.size > 0) {
    const sourcePath = configs[0]?.sourcePath
    if (!sourcePath) {
      throw new Error('Cannot render catalog imports without a source path.')
    }
    lines.push(
      `import type { ${[...catalogTypeImports].toSorted().join(', ')} } from '${moduleSpecifier(dirname(sourcePath), currentConfig().typesOutput)}'`
    )
  }
  lines.push(`import { createTypedSqlStatement } from '${currentConfig().packageImport}/runtime'`)

  return lines.join('\n')
}

function renderInterface(
  name: string,
  fields: readonly (
    | Pick<ResolvedSqlColumn, 'nullable' | 'propertyName' | 'tsType'>
    | Pick<ResolvedSqlParameter, 'nullable' | 'propertyName' | 'tsType'>
  )[]
): string {
  if (fields.length === 0) {
    return `export type ${name} = Record<string, never>`
  }

  return [
    `export interface ${name} {`,
    ...fields.map(
      (field) =>
        `  readonly ${quotePropertyName(field.propertyName)}: ${field.tsType}${'nullable' in field && field.nullable ? ' | null' : ''}`
    ),
    '}',
  ].join('\n')
}

function renderGeneratedTypeDeclaration(declaration: GeneratedJsonTypeDeclaration): string {
  return renderInterface(declaration.name, declaration.fields)
}

function renderColumnSourceMetadata(source: TypedSqlPostgresIrColumnSource): string {
  if (source.kind !== 'tableColumn') {
    return JSON.stringify(source)
  }

  const stableSource = {
    attname: source.attname,
    kind: source.kind,
    relname: source.relname,
    varlevelsup: source.varlevelsup,
    varno: source.varno,
    varnullingrels: source.varnullingrels,
  }
  return JSON.stringify(stableSource)
}

function renderColumnMetadata(columns: readonly ResolvedSqlColumn[]): string {
  if (columns.length === 0) {
    return '[]'
  }

  return `[
${columns
  .map(
    (column) => `    {
      name: ${quoteString(column.name)},
      nullable: ${column.nullable},
      pgType: ${quoteString(column.pgType)},
      pgTypeName: ${quoteString(column.pgTypeName)},
      pgTypeSchema: ${quoteString(column.pgTypeSchema)},
      propertyName: ${quoteString(column.propertyName)}${
        column.source ? `,\n      source: ${renderColumnSourceMetadata(column.source)}` : ''
      },
    }`
  )
  .join(',\n')},
  ]`
}

function renderParameterMetadata(parameters: readonly ResolvedSqlParameter[]): string {
  if (parameters.length === 0) {
    return '[]'
  }

  return `[
${parameters
  .map(
    (parameter) => `    {
      name: ${quoteString(parameter.name)},
      nullable: ${parameter.nullable},
      pgType: ${quoteString(parameter.pgType)},
      pgTypeName: ${quoteString(parameter.pgTypeName)},
      pgTypeSchema: ${quoteString(parameter.pgTypeSchema)},
      propertyName: ${quoteString(parameter.propertyName)},
    }`
  )
  .join(',\n')},
  ]`
}

function renderStatement(config: ResolvedTypedSql): string {
  const paramsName = `${pascalCaseIdentifier(config.name)}Params`
  const rowName = `${pascalCaseIdentifier(config.name)}Row`
  const parameterNames = config.parameterNames.map(quoteString).join(', ')
  const generatedTypeDeclarations =
    config.generatedTypeDeclarations.length > 0 ? `${config.generatedTypeDeclarations.join('\n\n')}\n\n` : ''

  return `${generatedTypeDeclarations}${renderInterface(paramsName, config.parameters)}

${renderInterface(rowName, config.columns)}

export const ${config.name} = createTypedSqlStatement<
  ${paramsName},
  ${rowName},
  ${quoteString(config.access)},
  ${quoteString(config.cardinality)}
>({
  access: ${quoteString(config.access)},
  columns: ${renderColumnMetadata(config.columns)},
  command: ${quoteString(config.command)},
  cardinality: ${quoteString(config.cardinality)},
  name: ${quoteString(config.name)},
  parameterNames: [${parameterNames}],
  parameters: ${renderParameterMetadata(config.parameters)},
  rowBounds: { min: ${config.rowBounds.min}, max: ${config.rowBounds.max ?? 'null'}, proof: ${quoteString(config.rowBounds.proof)} },
  text: ${quoteString(config.sql)},
})`
}

function renderTypedSql(config: ResolvedTypedSql): string {
  const sourcePath = `./${basename(config.sourcePath)}`
  return `// ${generatedByMarker}
// Source: ${sourcePath}
// DO NOT EDIT MANUALLY

${renderImports([config])}

${renderStatement(config)}
`
}

function assertColumnAssertions(config: CompiledTypedSql, resolvedColumns: readonly ResolvedSqlColumn[]): void {
  if (config.columns.length === 0) {
    return
  }

  const resolvedByName = new Map(resolvedColumns.map((column) => [column.name, column]))
  for (const assertion of config.columns) {
    const resolved = resolvedByName.get(assertion.name)
    if (!resolved) {
      throw new Error(`${config.sourceFile}: @column ${assertion.name} does not exist in the PostgreSQL result.`)
    }

    if (assertion.pgType && normalizePgTypeName(assertion.pgType) !== normalizePgTypeName(resolved.pgType)) {
      throw new Error(
        `${config.sourceFile}: result column ${assertion.name} type drift. Expected ${assertion.pgType}, PostgreSQL inferred ${resolved.pgType}.`
      )
    }
  }
}

async function inferDmlParameterNullability(
  client: PostgresQueryable,
  config: CompiledTypedSql
): Promise<ReadonlyMap<string, boolean>> {
  const targets = collectDmlParameterTargets(
    config.sql,
    config.parameters.map((parameter) => parameter.name)
  )
  if (targets.length === 0) {
    return new Map()
  }

  const { rows } = await client.query<{
    readonly attname: string
    readonly nullable: boolean
    readonly table_name: string
  }>(
    `select
       format('%I.%I', namespace.nspname, class.relname) as table_name,
       attribute.attname,
       not attribute.attnotnull as nullable
     from pg_catalog.pg_attribute attribute
     join pg_catalog.pg_class class
       on class.oid = attribute.attrelid
     join pg_catalog.pg_namespace namespace
       on namespace.oid = class.relnamespace
     where format('%I.%I', namespace.nspname, class.relname) = any($1::text[])
       and attribute.attnum > 0
       and not attribute.attisdropped`,
    [[...new Set(targets.map((target) => target.table))]]
  )

  const nullableByColumn = new Map(rows.map((row) => [`${row.table_name}.${row.attname}`, row.nullable]))
  const nullableByParameter = new Map<string, boolean>()
  for (const target of targets) {
    const nullable = nullableByColumn.get(`${target.table}.${target.column}`)
    if (nullable === undefined) {
      continue
    }

    nullableByParameter.set(target.parameter, (nullableByParameter.get(target.parameter) ?? true) && nullable)
  }

  return nullableByParameter
}

async function resolveTypedSqlWithAnalyzer(
  configs: readonly CompiledTypedSql[],
  client: PostgresQueryable
): Promise<ResolvedTypedSql[]> {
  const result = await buildTypedSqlPostgresIrFromCompiledConfigs(
    client,
    configs.map((config) => ({
      name: config.name,
      parameterNames: config.parameterNames,
      parameterTypes: config.parameterTypes,
      sourceFile: config.sourceFile,
      sql: config.sql,
    }))
  )

  const resolvedQueries: ResolvedTypedSql[] = []
  for (const [index, ir] of result.queries.entries()) {
    const config = configs[index]
    if (!config) {
      throw new Error(`PostgreSQL analyzer returned an unexpected extra query ${ir.name}.`)
    }

    const generatedDeclarations: GeneratedJsonTypeDeclaration[] = []
    const usedGeneratedTypeNames = new Map<string, number>()
    const columns = ir.resultColumns.map((column, columnIndex): ResolvedSqlColumn => {
      const name = column.name ?? `column_${columnIndex + 1}`
      const propertyName = camelCaseIdentifier(name)
      const suggestedJsonTypeName = `${pascalCaseIdentifier(config.name)}${pascalCaseIdentifier(propertyName)}Json`
      return {
        jsonShape: column.jsonShape,
        name,
        nullable: column.nullable,
        pgType: column.pgType,
        pgTypeName: column.pgTypeName,
        pgTypeSchema: column.pgTypeSchema,
        propertyName,
        source: column.source,
        tsType: column.jsonShape
          ? tsTypeForJsonShape(
              column.jsonShape,
              config.sourceFile,
              suggestedJsonTypeName,
              generatedDeclarations,
              usedGeneratedTypeNames
            )
          : column.tsType,
      }
    })
    assertColumnAssertions(config, columns)
    const parameterNullability = await inferDmlParameterNullability(client, config)

    const parameters = config.parameters.map((parameter, paramIndex): ResolvedSqlParameter => {
      const analyzed = ir.params[paramIndex]
      if (!analyzed) {
        throw new Error(`${config.sourceFile}: analyzer returned no type for parameter ${parameter.name}.`)
      }

      return {
        name: parameter.name,
        nullable: parameter.nullable === true ? true : (parameterNullability.get(parameter.name) ?? false),
        pgType: analyzed.pgType,
        pgTypeName: analyzed.pgTypeName,
        pgTypeSchema: analyzed.pgTypeSchema,
        propertyName: parameter.propertyName,
        tsType:
          analyzed.tsTypeSource === 'checkConstraint'
            ? analyzed.tsType
            : parameterTsTypeForPgType(analyzed.pgType, config.sourceFile, analyzed.pgTypeSchema, analyzed.pgTypeName),
      }
    })

    resolvedQueries.push({
      columns,
      access:
        config.access ??
        (ir.hasDataModifyingCte ? 'write' : typedSqlAccessForCommand(typedSqlCommandFromPostgres(ir.command))),
      cardinality: ir.rowCardinality,
      command: typedSqlCommandFromPostgres(ir.command),
      generatedTypeDeclarations: generatedDeclarations.map(renderGeneratedTypeDeclaration),
      name: config.name,
      outputPath: config.outputPath,
      parameters,
      parameterNames: config.parameterNames,
      parameterTypes: parameters.map((parameter) => parameter.pgType),
      rowBounds: ir.rowBounds,
      sourceFile: config.sourceFile,
      sourcePath: config.sourcePath,
      sql: config.sql,
    })
  }

  return resolvedQueries
}

async function findGeneratedTypedSqlFiles(): Promise<string[]> {
  const generatedFiles: string[] = []
  async function walk(directory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true })
    for (const entry of entries) {
      const entryPath = join(directory, entry.name)
      if (entry.isDirectory()) {
        if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
          await walk(entryPath)
        }
        continue
      }

      if (
        entry.isFile() &&
        (entry.name.endsWith(typedSqlOutputSuffix) ||
          legacyTypedSqlOutputSuffixes.some((suffix) => entry.name.endsWith(suffix)))
      ) {
        generatedFiles.push(entryPath)
      }
    }
  }

  for (const includeRoot of currentConfig().include) {
    await walk(includeRoot)
  }
  return generatedFiles
}

async function removeStaleGeneratedFiles(configs: readonly ResolvedTypedSql[]): Promise<number> {
  const expectedOutputPaths = new Set(configs.map((config) => config.outputPath))
  let removed = 0
  for (const generatedPath of await findGeneratedTypedSqlFiles()) {
    if (expectedOutputPaths.has(generatedPath)) {
      continue
    }

    const contents = readFileSync(generatedPath, 'utf8')
    if (!contents.includes(generatedByMarker)) {
      continue
    }

    await rm(generatedPath)
    removed += 1
  }
  return removed
}

async function writeGeneratedFiles(configs: readonly ResolvedTypedSql[]): Promise<void> {
  for (const config of configs) {
    await mkdir(dirname(config.outputPath), { recursive: true })
    await writeFile(config.outputPath, renderTypedSql(config))
  }
}

export interface GenerateTypedSqlResult {
  readonly generatedFiles: readonly string[]
  readonly removedFiles: number
  readonly statementCount: number
}

export async function generateTypedSql(config: PostgresTypedSqlConfig): Promise<GenerateTypedSqlResult> {
  if (generationInProgress) {
    throw new Error('Concurrent generation in one process is not supported.')
  }

  generationInProgress = true
  activeConfig = resolveConfig(config)
  let database: Awaited<ReturnType<typeof createAnalysisDatabase>> | undefined

  try {
    database = await createAnalysisDatabase({
      extensions: activeConfig.extensions,
      schemaFiles: activeConfig.schemaFiles,
    })
    await generateCatalogTypes(database, activeConfig)
    const rawConfigs = await readTypedSqlConfigs()
    assertUniqueTypedSqlNames(rawConfigs)
    const configs = rawConfigs.map(compileTypedSql)
    const resolvedConfigs = await resolveTypedSqlWithAnalyzer(configs, database)

    await writeGeneratedFiles(resolvedConfigs)
    const removedFiles = await removeStaleGeneratedFiles(resolvedConfigs)
    return {
      generatedFiles: resolvedConfigs.map((entry) => entry.outputPath),
      removedFiles,
      statementCount: configs.length,
    }
  } finally {
    await database?.close()
    activeConfig = undefined
    generationInProgress = false
  }
}
