import { randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'

import {
  buildTypedSqlPostgresIrFromCompiledConfigs,
  type TypedSqlPostgresIrColumnSource,
  type TypedSqlPostgresIrJsonShape,
  type TypedSqlPostgresIrRowBounds,
  type TypedSqlPostgresIrRowCardinality,
} from './analyzer-ir.js'
import { buildCatalogTypes } from './catalog-generator.js'
import type { ResolvedPostgresTypedSqlConfig } from './config.js'
import { resolveConfig, type PostgresTypedSqlConfig } from './config.js'
import type { PostgresQueryable } from './database.js'
import { createAnalysisDatabase } from './engine.js'
import {
  normalizePostgresTypeName as normalizePgTypeName,
  postgresArrayElementType,
  postgresTypeScriptScalarImports as dbScalarTypes,
  type PostgresScalarProfile,
  typeScriptParameterTypeForPostgresType,
  typeScriptTypeForPostgresType,
} from './postgres-types.js'
import { compileNamedParameters, parseTypedSqlSource } from './sql-source.js'
import {
  assertTypeScriptBindingIdentifier,
  assertUniqueTypeScriptBindings,
  pascalCaseIdentifier,
  quotePropertyName,
  type TypeScriptBinding,
} from './typescript-names.js'

let generationInProgress = false
const typedSqlSourceSuffix = '.typed.sql'
const typedSqlOutputSuffix = '.typed-sql.ts'
const legacyTypedSqlOutputSuffixes = ['.typed.sql.ts']
const generatedByMarker = 'This file is auto-generated by postgres-typed-sql'
const generatedMarkerLine = `// ${generatedByMarker}`
const ignoredDiscoveryDirectories = new Set([
  '.git',
  '.next',
  '.turbo',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'out',
  'playwright-report',
  'reports',
  'test-results',
])

interface SqlParameter {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
  readonly propertyName: string
}

interface SqlColumn {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
  readonly propertyName: string
}

interface TypedSqlConfig {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameter[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface CompiledTypedSql {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameter[]
  readonly parameterNames: readonly string[]
  readonly parameterTypes: readonly (string | undefined)[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface ResolvedSqlParameter {
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly tsType: string
}

interface ResolvedSqlColumn {
  readonly jsonShape?: TypedSqlPostgresIrJsonShape
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly source: TypedSqlPostgresIrColumnSource | null
  readonly tsType: string
}

type TypedSqlCommand = 'delete' | 'insert' | 'merge' | 'select' | 'unknown' | 'update'
type TypedSqlAccess = 'read' | 'write'

interface ResolvedTypedSql {
  readonly access: TypedSqlAccess
  readonly catalogTypeImports: readonly string[]
  readonly cardinality: TypedSqlPostgresIrRowCardinality
  readonly columns: readonly ResolvedSqlColumn[]
  readonly command: TypedSqlCommand
  readonly generatedTypeDeclarations: readonly string[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly ResolvedSqlParameter[]
  readonly parameterNames: readonly string[]
  readonly parameterTypes: readonly string[]
  readonly rowBounds: TypedSqlPostgresIrRowBounds
  readonly scalarTypeImports: readonly string[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface TypeScriptImports {
  readonly catalog: Set<string>
  readonly scalar: Set<string>
}

const jsonNumberPgTypes = new Set(['bigint', 'double precision', 'integer', 'numeric', 'oid', 'real', 'smallint'])

function requireSqlName(value: string, sourceFile: string): string {
  if (!/^[a-z][A-Za-z0-9]*$/u.test(value)) {
    throw new Error(`${sourceFile}: @name must be a lower camel-case identifier.`)
  }
  assertTypeScriptBindingIdentifier(value, `${sourceFile}: @name`)
  if (value === 'createTypedSqlStatement') {
    throw new Error(`${sourceFile}: @name createTypedSqlStatement collides with the generated runtime import.`)
  }

  return value
}

function lowerCamelCaseFromPathBase(base: string): string {
  const parts = base.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0)
  if (parts.length === 0) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const [head, ...tail] = parts
  if (!head) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const identifier = [
    head.toLowerCase(),
    ...tail.map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`),
  ].join('')

  return requireSqlName(identifier, base)
}

function quoteString(value: string): string {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll('\t', '\\t')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')

  return value.includes("'") ? `"${escaped.replaceAll('"', '\\"')}"` : `'${escaped.replaceAll("'", "\\'")}'`
}

function relativePath(config: ResolvedPostgresTypedSqlConfig, filePath: string): string {
  return relative(config.rootDir, filePath)
}

function tsTypeForPgType(
  pgType: string,
  sourceFile: string,
  scalarProfile: PostgresScalarProfile,
  typeSchema = 'pg_catalog',
  typeName = ''
): string {
  return typeScriptTypeForPostgresType(
    { pgType, pgTypeName: typeName, pgTypeSchema: typeSchema },
    sourceFile,
    scalarProfile
  )
}

function parameterTsTypeForPgType(
  pgType: string,
  sourceFile: string,
  scalarProfile: PostgresScalarProfile,
  typeSchema = 'pg_catalog',
  typeName = ''
): string {
  return typeScriptParameterTypeForPostgresType(
    { pgType, pgTypeName: typeName, pgTypeSchema: typeSchema },
    sourceFile,
    scalarProfile
  )
}

function collectPgTypeImports(
  imports: TypeScriptImports,
  pgType: string,
  typeSchema = 'pg_catalog',
  typeName = '',
  usage: 'input' | 'output' = 'output',
  scalarProfile: PostgresScalarProfile = 'node-postgres'
): void {
  const arrayElementType = postgresArrayElementType(pgType, typeName)
  if (arrayElementType) {
    collectPgTypeImports(imports, arrayElementType, typeSchema, arrayElementType, usage, scalarProfile)
    return
  }

  if (typeSchema !== 'pg_catalog') {
    const tsType = typeScriptTypeForPostgresType(
      { pgType, pgTypeName: typeName, pgTypeSchema: typeSchema },
      undefined,
      scalarProfile
    )
    if (tsType !== 'unknown') {
      imports.catalog.add(tsType)
    }
    return
  }

  const tsType =
    usage === 'input'
      ? typeScriptParameterTypeForPostgresType(
          { pgType, pgTypeName: typeName, pgTypeSchema: typeSchema },
          undefined,
          scalarProfile
        )
      : typeScriptTypeForPostgresType(
          { pgType, pgTypeName: typeName, pgTypeSchema: typeSchema },
          undefined,
          scalarProfile
        )
  if (dbScalarTypes.has(tsType)) {
    imports.scalar.add(tsType)
  }
}

function collectResolvedTypeImports(
  imports: TypeScriptImports,
  tsType: string,
  pgType: string,
  typeSchema: string,
  typeName: string,
  sourceFile: string,
  usage: 'input' | 'output',
  scalarProfile: PostgresScalarProfile
): void {
  const defaultType =
    usage === 'input'
      ? parameterTsTypeForPgType(pgType, sourceFile, scalarProfile, typeSchema, typeName)
      : tsTypeForPgType(pgType, sourceFile, scalarProfile, typeSchema, typeName)
  if (tsType === defaultType) {
    collectPgTypeImports(imports, pgType, typeSchema, typeName, usage, scalarProfile)
  } else if (dbScalarTypes.has(tsType)) {
    imports.scalar.add(tsType)
  } else {
    imports.catalog.add(tsType)
  }
}

function typedSqlCommandFromPostgres(command: string): TypedSqlCommand {
  switch (command.toLowerCase()) {
    case 'delete':
      return 'delete'
    case 'insert':
      return 'insert'
    case 'merge':
      return 'merge'
    case 'select':
      return 'select'
    case 'update':
      return 'update'
    default:
      return 'unknown'
  }
}

function typedSqlAccessForCommand(command: TypedSqlCommand): TypedSqlAccess {
  return command === 'select' ? 'read' : 'write'
}

function parseDirectivePgType(pgType: string | undefined): {
  readonly nullable: boolean
  readonly pgType?: string
} {
  if (!pgType) {
    return { nullable: false }
  }

  if (pgType === '?') {
    return { nullable: true }
  }

  if (pgType.endsWith('?')) {
    const typeWithoutSuffix = pgType.slice(0, -1).trimEnd()
    return { nullable: true, ...(typeWithoutSuffix ? { pgType: typeWithoutSuffix } : {}) }
  }

  return { nullable: false, pgType }
}

async function walkTypedSqlFiles(directory: string, output: string[]): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true })
  for (const entry of entries) {
    const entryPath = join(directory, entry.name)
    if (entry.isDirectory()) {
      if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
        await walkTypedSqlFiles(entryPath, output)
      }
      continue
    }

    if (entry.isFile() && entry.name.endsWith(typedSqlSourceSuffix)) {
      output.push(entryPath)
    }
  }
}

async function findTypedSqlSourceFiles(config: ResolvedPostgresTypedSqlConfig): Promise<string[]> {
  const sourceFiles = new Set<string>()
  for (const includeRoot of config.include) {
    const entries: string[] = []
    await walkTypedSqlFiles(includeRoot, entries)
    for (const entry of entries) {
      sourceFiles.add(entry)
    }
  }
  return [...sourceFiles].toSorted((left, right) =>
    relativePath(config, left).localeCompare(relativePath(config, right))
  )
}

function generatedOutputPath(sourcePath: string): string {
  return `${sourcePath.slice(0, -typedSqlSourceSuffix.length)}${typedSqlOutputSuffix}`
}

async function readTypedSqlConfigs(generatorConfig: ResolvedPostgresTypedSqlConfig): Promise<TypedSqlConfig[]> {
  const sourcePaths = await findTypedSqlSourceFiles(generatorConfig)
  const configs: TypedSqlConfig[] = []

  for (const sourcePath of sourcePaths) {
    const sourceFile = relativePath(generatorConfig, sourcePath)
    const text = readFileSync(sourcePath, 'utf8')
    const parsedSource = parseTypedSqlSource(text, sourceFile)
    const defaultName = lowerCamelCaseFromPathBase(basename(sourceFile, typedSqlSourceSuffix))
    let access: TypedSqlAccess | undefined
    let name = defaultName
    const parameters: SqlParameter[] = []
    const columns: SqlColumn[] = []
    const firstColumnDirectiveByName = new Map<string, string>()
    const firstParameterDirectiveByName = new Map<string, string>()

    for (const directive of parsedSource.directives) {
      const location = `${sourceFile}:${directive.line}`
      const kind = directive.kind
      const bodyParts = /^(\S+)(?:\s+([\s\S]*))?$/u.exec(directive.body)
      const identifier = bodyParts?.[1]
      const rawPgType = bodyParts?.[2]?.trim()
      const parsedPgType = parseDirectivePgType(rawPgType)
      const pgType = parsedPgType.pgType
      if (kind === 'name') {
        if (!identifier || rawPgType) {
          throw new Error(`${location}: @name requires exactly one identifier.`)
        }

        name = requireSqlName(identifier, location)
        continue
      }

      if (kind === 'access') {
        if ((identifier !== 'read' && identifier !== 'write') || rawPgType) {
          throw new Error(`${location}: @access requires exactly read or write.`)
        }

        access = identifier
        continue
      }

      if (kind !== 'param' && kind !== 'column') {
        throw new Error(`${location}: unsupported typed SQL directive @${kind}.`)
      }

      if (!identifier) {
        throw new Error(`${location}: @${kind} requires a name.`)
      }
      if (kind === 'param' && !/^[A-Za-z_][A-Za-z0-9_]*$/u.test(identifier)) {
        throw new Error(`${location}: @param requires a named-parameter identifier.`)
      }
      if (kind === 'column' && parsedPgType.nullable) {
        throw new Error(`${location}: @column does not support ?; PostgreSQL determines result nullability.`)
      }

      const firstDirectiveByName = kind === 'param' ? firstParameterDirectiveByName : firstColumnDirectiveByName
      const firstLocation = firstDirectiveByName.get(identifier)
      if (firstLocation) {
        throw new Error(`${location}: duplicate @${kind} ${identifier}; first declared at ${firstLocation}.`)
      }
      firstDirectiveByName.set(identifier, location)

      const entry = {
        name: identifier,
        nullable: parsedPgType.nullable,
        pgType,
        propertyName: identifier,
      }

      if (kind === 'param') {
        parameters.push(entry)
      } else {
        columns.push(entry)
      }
    }

    configs.push({
      access,
      columns,
      name,
      outputPath: generatedOutputPath(sourcePath),
      parameters,
      sourceFile,
      sourcePath,
      sql: parsedSource.sql,
    })
  }

  return configs
}

function assertUniqueTypedSqlNames(configs: readonly TypedSqlConfig[]): void {
  const firstSourceByName = new Map<string, string>()
  for (const config of configs) {
    const firstSource = firstSourceByName.get(config.name)
    if (firstSource) {
      throw new Error(`${config.sourceFile}: typed SQL statement name ${config.name} already used by ${firstSource}.`)
    }
    firstSourceByName.set(config.name, config.sourceFile)
  }
}

function compileTypedSql(config: TypedSqlConfig): CompiledTypedSql {
  const parametersByName = new Map(config.parameters.map((parameter) => [parameter.name, parameter]))
  const compiled = compileNamedParameters(config.sql, config.sourceFile)
  const parameterTypes: (string | undefined)[] = []
  const parameters: SqlParameter[] = []
  const parameterNames = compiled.parameterNames.map((name) => {
    const parameter =
      parametersByName.get(name) ??
      ({
        name,
        propertyName: name,
      } satisfies SqlParameter)

    parameters.push(parameter)
    parameterTypes.push(parameter.pgType)
    return parameter.propertyName
  })

  const unusedParameters = config.parameters.filter(
    (parameter) => !parameters.some((used) => used.name === parameter.name)
  )
  if (unusedParameters.length > 0) {
    throw new Error(
      `${config.sourceFile}: declared parameter(s) not used: ${unusedParameters.map((parameter) => parameter.name).join(', ')}.`
    )
  }

  return {
    access: config.access,
    columns: config.columns,
    name: config.name,
    outputPath: config.outputPath,
    parameters,
    parameterNames,
    parameterTypes,
    sourceFile: config.sourceFile,
    sourcePath: config.sourcePath,
    sql: compiled.sql,
  }
}

interface GeneratedJsonTypeDeclaration {
  readonly fields: readonly {
    readonly nullable: boolean
    readonly propertyName: string
    readonly tsType: string
  }[]
  readonly name: string
}

function assertUniquePublicNames(names: readonly string[], kind: string, sourceFile: string): void {
  const firstIndexByName = new Map<string, number>()
  for (const [index, name] of names.entries()) {
    const firstIndex = firstIndexByName.get(name)
    if (firstIndex !== undefined) {
      throw new Error(
        `${sourceFile}: duplicate ${kind} name ${JSON.stringify(name)} at positions ${firstIndex + 1} and ${index + 1}.`
      )
    }
    firstIndexByName.set(name, index)
  }
}

function reserveGeneratedTypeBinding(
  bindings: Map<string, string>,
  name: string,
  source: string,
  sourceFile: string
): void {
  assertTypeScriptBindingIdentifier(name, `${sourceFile}: generated type for ${source}`)
  const firstSource = bindings.get(name)
  if (firstSource) {
    throw new Error(
      `${sourceFile}: generated TypeScript binding ${name} for ${source} collides with ${firstSource}. Alias the SQL field to give it a distinct name.`
    )
  }
  bindings.set(name, source)
}

function singularTypeName(name: string): string {
  return name.endsWith('Rows')
    ? name.slice(0, -1)
    : name.endsWith('ies')
      ? `${name.slice(0, -3)}y`
      : name.endsWith('ses')
        ? name.slice(0, -2)
        : name.endsWith('s') && name.length > 1
          ? name.slice(0, -1)
          : name
}

function scalarTsTypeForJsonShape(
  shape: Extract<TypedSqlPostgresIrJsonShape, { readonly kind: 'scalar' }>,
  sourceFile: string,
  imports: TypeScriptImports
): string {
  if (shape.tsType) {
    imports.catalog.add(shape.tsType)
    return shape.tsType
  }

  if (shape.pgType === 'unknown' || shape.pgTypeName === 'unknown' || shape.pgTypeSchema === 'unknown') {
    imports.scalar.add('DbJsonSelected')
    return 'DbJsonSelected'
  }

  if (shape.pgTypeSchema === 'pg_catalog') {
    const normalizedTypeName = normalizePgTypeName(shape.pgType)
    if (normalizedTypeName === 'boolean') {
      return 'boolean'
    }
    if (jsonNumberPgTypes.has(normalizedTypeName)) {
      return 'number'
    }
    if (!postgresArrayElementType(shape.pgType, shape.pgTypeName)) {
      return 'string'
    }
  }

  collectPgTypeImports(imports, shape.pgType, shape.pgTypeSchema, shape.pgTypeName)
  return tsTypeForPgType(shape.pgType, sourceFile, 'node-postgres', shape.pgTypeSchema, shape.pgTypeName)
}

function tsTypeForJsonShape(
  shape: TypedSqlPostgresIrJsonShape,
  sourceFile: string,
  suggestedName: string,
  declarations: GeneratedJsonTypeDeclaration[],
  usedNames: Map<string, string>,
  imports: TypeScriptImports
): string {
  switch (shape.kind) {
    case 'array':
      return `readonly ${tsTypeForJsonShape(
        shape.element,
        sourceFile,
        singularTypeName(suggestedName),
        declarations,
        usedNames,
        imports
      )}[]`
    case 'object': {
      reserveGeneratedTypeBinding(usedNames, suggestedName, `JSON object ${suggestedName}`, sourceFile)
      assertUniquePublicNames(
        shape.fields.map((field) => field.name),
        `JSON field in ${suggestedName}`,
        sourceFile
      )
      const name = suggestedName
      declarations.push({
        fields: shape.fields.map((field) => ({
          nullable: field.shape.nullable,
          propertyName: field.name,
          tsType: tsTypeForJsonShape(
            field.shape,
            sourceFile,
            `${name}${pascalCaseIdentifier(field.name)}`,
            declarations,
            usedNames,
            imports
          ),
        })),
        name,
      })
      return name
    }
    case 'opaque':
      imports.scalar.add('DbJsonSelected')
      return 'DbJsonSelected'
    case 'scalar':
      return scalarTsTypeForJsonShape(shape, sourceFile, imports)
  }
}

function moduleSpecifier(fromDirectory: string, targetPath: string): string {
  const withoutExtension = targetPath.replace(/\.tsx?$/u, '')
  const path = relative(fromDirectory, withoutExtension).replaceAll('\\', '/')
  return `${path.startsWith('.') ? path : `./${path}`}.js`
}

function renderImports(configs: readonly ResolvedTypedSql[], generatorConfig: ResolvedPostgresTypedSqlConfig): string {
  const scalarImports = new Set<string>()
  const catalogTypeImports = new Set<string>()
  for (const config of configs) {
    for (const identifier of config.scalarTypeImports) {
      scalarImports.add(identifier)
    }
    for (const identifier of config.catalogTypeImports) {
      catalogTypeImports.add(identifier)
    }
  }

  const lines: string[] = []
  if (scalarImports.size > 0) {
    lines.push(
      `import type { ${[...scalarImports].toSorted().join(', ')} } from '${generatorConfig.packageImport}/scalars'`
    )
  }
  if (catalogTypeImports.size > 0) {
    const sourcePath = configs[0]?.sourcePath
    if (!sourcePath) {
      throw new Error('Cannot render catalog imports without a source path.')
    }
    lines.push(
      `import type { ${[...catalogTypeImports].toSorted().join(', ')} } from '${moduleSpecifier(dirname(sourcePath), generatorConfig.typesOutput)}'`
    )
  }
  lines.push(`import { createTypedSqlStatement } from '${generatorConfig.packageImport}/runtime'`)

  return lines.join('\n')
}

function renderInterface(
  name: string,
  fields: readonly (
    | Pick<ResolvedSqlColumn, 'nullable' | 'propertyName' | 'tsType'>
    | Pick<ResolvedSqlParameter, 'nullable' | 'propertyName' | 'tsType'>
  )[]
): string {
  if (fields.length === 0) {
    return `export type ${name} = Record<string, never>`
  }

  return [
    `export interface ${name} {`,
    ...fields.map(
      (field) =>
        `  readonly ${quotePropertyName(field.propertyName)}: ${field.tsType}${'nullable' in field && field.nullable ? ' | null' : ''}`
    ),
    '}',
  ].join('\n')
}

function renderGeneratedTypeDeclaration(declaration: GeneratedJsonTypeDeclaration): string {
  return renderInterface(declaration.name, declaration.fields)
}

function renderColumnSourceMetadata(source: TypedSqlPostgresIrColumnSource): string {
  if (source.kind !== 'tableColumn') {
    return JSON.stringify(source)
  }

  const stableSource = {
    attname: source.attname,
    kind: source.kind,
    relname: source.relname,
    varlevelsup: source.varlevelsup,
    varno: source.varno,
    varnullingrels: source.varnullingrels,
  }
  return JSON.stringify(stableSource)
}

function renderColumnMetadata(columns: readonly ResolvedSqlColumn[]): string {
  if (columns.length === 0) {
    return '[]'
  }

  return `[
${columns
  .map(
    (column) => `    {
      name: ${quoteString(column.name)},
      nullable: ${column.nullable},
      pgType: ${quoteString(column.pgType)},
      pgTypeName: ${quoteString(column.pgTypeName)},
      pgTypeSchema: ${quoteString(column.pgTypeSchema)},
      propertyName: ${quoteString(column.propertyName)}${
        column.source ? `,\n      source: ${renderColumnSourceMetadata(column.source)}` : ''
      },
    }`
  )
  .join(',\n')},
  ]`
}

function renderParameterMetadata(parameters: readonly ResolvedSqlParameter[]): string {
  if (parameters.length === 0) {
    return '[]'
  }

  return `[
${parameters
  .map(
    (parameter) => `    {
      name: ${quoteString(parameter.name)},
      nullable: ${parameter.nullable},
      pgType: ${quoteString(parameter.pgType)},
      pgTypeName: ${quoteString(parameter.pgTypeName)},
      pgTypeSchema: ${quoteString(parameter.pgTypeSchema)},
      propertyName: ${quoteString(parameter.propertyName)},
    }`
  )
  .join(',\n')},
  ]`
}

function renderStatement(config: ResolvedTypedSql): string {
  const paramsName = `${pascalCaseIdentifier(config.name)}Params`
  const rowName = `${pascalCaseIdentifier(config.name)}Row`
  const parameterNames = config.parameterNames.map(quoteString).join(', ')
  const generatedTypeDeclarations =
    config.generatedTypeDeclarations.length > 0 ? `${config.generatedTypeDeclarations.join('\n\n')}\n\n` : ''

  return `${generatedTypeDeclarations}${renderInterface(paramsName, config.parameters)}

${renderInterface(rowName, config.columns)}

export const ${config.name} = createTypedSqlStatement<
  ${paramsName},
  ${rowName},
  ${quoteString(config.access)},
  ${quoteString(config.cardinality)}
>({
  access: ${quoteString(config.access)},
  columns: ${renderColumnMetadata(config.columns)},
  command: ${quoteString(config.command)},
  cardinality: ${quoteString(config.cardinality)},
  name: ${quoteString(config.name)},
  parameterNames: [${parameterNames}],
  parameters: ${renderParameterMetadata(config.parameters)},
  rowBounds: { min: ${config.rowBounds.min}, max: ${config.rowBounds.max ?? 'null'}, proof: ${quoteString(config.rowBounds.proof)} },
  text: ${quoteString(config.sql)},
})`
}

function renderTypedSql(config: ResolvedTypedSql, generatorConfig: ResolvedPostgresTypedSqlConfig): string {
  const sourcePath = `./${basename(config.sourcePath)}`
  return `// ${generatedByMarker}
// Source: ${sourcePath}
// DO NOT EDIT MANUALLY

${renderImports([config], generatorConfig)}

${renderStatement(config)}
`
}

function assertColumnAssertions(config: CompiledTypedSql, resolvedColumns: readonly ResolvedSqlColumn[]): void {
  if (config.columns.length === 0) {
    return
  }

  const resolvedByName = new Map(resolvedColumns.map((column) => [column.name, column]))
  for (const assertion of config.columns) {
    const resolved = resolvedByName.get(assertion.name)
    if (!resolved) {
      throw new Error(`${config.sourceFile}: @column ${assertion.name} does not exist in the PostgreSQL result.`)
    }

    if (assertion.pgType && normalizePgTypeName(assertion.pgType) !== normalizePgTypeName(resolved.pgType)) {
      throw new Error(
        `${config.sourceFile}: result column ${assertion.name} type drift. Expected ${assertion.pgType}, PostgreSQL inferred ${resolved.pgType}.`
      )
    }
  }
}

async function resolveTypedSqlWithAnalyzer(
  configs: readonly CompiledTypedSql[],
  client: PostgresQueryable,
  generatorConfig: ResolvedPostgresTypedSqlConfig
): Promise<ResolvedTypedSql[]> {
  const result = await buildTypedSqlPostgresIrFromCompiledConfigs(
    client,
    configs.map((config) => ({
      name: config.name,
      parameterNames: config.parameterNames,
      parameterTypes: config.parameterTypes,
      sourceFile: config.sourceFile,
      sql: config.sql,
    }))
  )

  const resolvedQueries: ResolvedTypedSql[] = []
  for (const [index, ir] of result.queries.entries()) {
    const config = configs[index]
    if (!config) {
      throw new Error(`PostgreSQL analyzer returned an unexpected extra query ${ir.name}.`)
    }

    const generatedDeclarations: GeneratedJsonTypeDeclaration[] = []
    const typeImports: TypeScriptImports = {
      catalog: new Set(),
      scalar: new Set(),
    }
    const statementTypeBindings: TypeScriptBinding[] = [
      { name: `${pascalCaseIdentifier(config.name)}Params`, source: 'parameter interface' },
      { name: `${pascalCaseIdentifier(config.name)}Row`, source: 'row interface' },
    ]
    assertUniqueTypeScriptBindings(statementTypeBindings, config.sourceFile)
    const usedGeneratedTypeNames = new Map(statementTypeBindings.map((binding) => [binding.name, binding.source]))
    const columns = ir.resultColumns.map((column, columnIndex): ResolvedSqlColumn => {
      const name = column.name ?? `column_${columnIndex + 1}`
      const propertyName = name
      const suggestedJsonTypeName = `${pascalCaseIdentifier(config.name)}${pascalCaseIdentifier(propertyName)}Json`
      const useStructuredJson = generatorConfig.scalarProfile === 'node-postgres' && column.jsonShape !== undefined
      const tsType =
        useStructuredJson && column.jsonShape
          ? tsTypeForJsonShape(
              column.jsonShape,
              config.sourceFile,
              suggestedJsonTypeName,
              generatedDeclarations,
              usedGeneratedTypeNames,
              typeImports
            )
          : generatorConfig.scalarProfile === 'node-postgres' && column.tsTypeSource === 'checkConstraint'
            ? column.tsType
            : tsTypeForPgType(
                column.pgType,
                config.sourceFile,
                generatorConfig.scalarProfile,
                column.pgTypeSchema,
                column.pgTypeName
              )
      if (!useStructuredJson) {
        collectResolvedTypeImports(
          typeImports,
          tsType,
          column.pgType,
          column.pgTypeSchema,
          column.pgTypeName,
          config.sourceFile,
          'output',
          generatorConfig.scalarProfile
        )
      }
      return {
        jsonShape: column.jsonShape,
        name,
        nullable: column.nullable,
        pgType: column.pgType,
        pgTypeName: column.pgTypeName,
        pgTypeSchema: column.pgTypeSchema,
        propertyName,
        source: column.source,
        tsType,
      }
    })
    assertUniquePublicNames(
      columns.map((column) => column.propertyName),
      'result column',
      config.sourceFile
    )
    assertColumnAssertions(config, columns)
    const parameters = config.parameters.map((parameter, paramIndex): ResolvedSqlParameter => {
      const analyzed = ir.params[paramIndex]
      if (!analyzed) {
        throw new Error(`${config.sourceFile}: analyzer returned no type for parameter ${parameter.name}.`)
      }

      const tsType =
        generatorConfig.scalarProfile === 'node-postgres' && analyzed.tsTypeSource === 'checkConstraint'
          ? analyzed.tsType
          : parameterTsTypeForPgType(
              analyzed.pgType,
              config.sourceFile,
              generatorConfig.scalarProfile,
              analyzed.pgTypeSchema,
              analyzed.pgTypeName
            )
      collectResolvedTypeImports(
        typeImports,
        tsType,
        analyzed.pgType,
        analyzed.pgTypeSchema,
        analyzed.pgTypeName,
        config.sourceFile,
        'input',
        generatorConfig.scalarProfile
      )
      return {
        name: parameter.name,
        nullable: parameter.nullable === true ? true : analyzed.nullable,
        pgType: analyzed.pgType,
        pgTypeName: analyzed.pgTypeName,
        pgTypeSchema: analyzed.pgTypeSchema,
        propertyName: parameter.propertyName,
        tsType,
      }
    })
    assertUniquePublicNames(
      parameters.map((parameter) => parameter.propertyName),
      'parameter',
      config.sourceFile
    )
    assertUniqueTypeScriptBindings(
      [
        { name: 'Record', source: 'reserved TypeScript utility type' },
        ...[...usedGeneratedTypeNames].map(([name, source]) => ({ name, source })),
        ...[...typeImports.catalog].map((name) => ({ name, source: 'catalog type import' })),
        ...[...typeImports.scalar].map((name) => ({ name, source: 'postgres-typed-sql scalar type import' })),
      ],
      config.sourceFile
    )

    resolvedQueries.push({
      columns,
      access:
        config.access ?? (ir.isWrite ? 'write' : typedSqlAccessForCommand(typedSqlCommandFromPostgres(ir.command))),
      cardinality: ir.rowCardinality,
      catalogTypeImports: [...typeImports.catalog].toSorted(),
      command: typedSqlCommandFromPostgres(ir.command),
      generatedTypeDeclarations: generatedDeclarations.map(renderGeneratedTypeDeclaration),
      name: config.name,
      outputPath: config.outputPath,
      parameters,
      parameterNames: config.parameterNames,
      parameterTypes: parameters.map((parameter) => parameter.pgType),
      rowBounds: ir.rowBounds,
      scalarTypeImports: [...typeImports.scalar].toSorted(),
      sourceFile: config.sourceFile,
      sourcePath: config.sourcePath,
      sql: config.sql,
    })
  }

  return resolvedQueries
}

async function findGeneratedTypedSqlFiles(config: ResolvedPostgresTypedSqlConfig): Promise<string[]> {
  const generatedFiles = new Set<string>()
  async function walk(directory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true })
    for (const entry of entries) {
      const entryPath = join(directory, entry.name)
      if (entry.isDirectory()) {
        if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
          await walk(entryPath)
        }
        continue
      }

      if (
        entry.isFile() &&
        (entry.name.endsWith(typedSqlOutputSuffix) ||
          legacyTypedSqlOutputSuffixes.some((suffix) => entry.name.endsWith(suffix)))
      ) {
        generatedFiles.add(entryPath)
      }
    }
  }

  for (const includeRoot of config.include) {
    await walk(includeRoot)
  }
  return [...generatedFiles].toSorted()
}

async function removeStaleGeneratedFiles(
  configs: readonly ResolvedTypedSql[],
  generatorConfig: ResolvedPostgresTypedSqlConfig
): Promise<number> {
  const expectedOutputPaths = new Set(configs.map((config) => config.outputPath))
  let removed = 0
  for (const generatedPath of await findGeneratedTypedSqlFiles(generatorConfig)) {
    if (expectedOutputPaths.has(generatedPath)) {
      continue
    }

    const contents = await readFile(generatedPath, 'utf8')
    if (
      contents !== generatedMarkerLine &&
      !contents.startsWith(`${generatedMarkerLine}\n`) &&
      !contents.startsWith(`${generatedMarkerLine}\r\n`)
    ) {
      continue
    }

    await rm(generatedPath)
    removed += 1
  }
  return removed
}

interface GeneratedOutput {
  readonly contents: string
  readonly outputPath: string
}

interface StagedGeneratedOutput extends GeneratedOutput {
  readonly backupPath: string
  readonly existed: boolean
  readonly stagedPath: string
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT'
}

async function existingContents(outputPath: string): Promise<string | null> {
  try {
    return await readFile(outputPath, 'utf8')
  } catch (error) {
    if (isMissingFileError(error)) {
      return null
    }
    throw error
  }
}

async function cleanStagingFiles(staged: readonly StagedGeneratedOutput[]): Promise<void> {
  await Promise.allSettled(
    staged.flatMap((entry) => [rm(entry.stagedPath, { force: true }), rm(entry.backupPath, { force: true })])
  )
}

async function rollbackGeneratedOutputs(
  installed: readonly StagedGeneratedOutput[],
  backedUp: readonly StagedGeneratedOutput[]
): Promise<unknown[]> {
  const errors: unknown[] = []
  for (const entry of installed.toReversed()) {
    try {
      await rm(entry.outputPath, { force: true })
    } catch (error) {
      errors.push(error)
    }
  }
  for (const entry of backedUp.toReversed()) {
    try {
      await rename(entry.backupPath, entry.outputPath)
    } catch (error) {
      errors.push(error)
    }
  }
  return errors
}

async function commitGeneratedOutputs(outputs: readonly GeneratedOutput[]): Promise<void> {
  const outputByPath = new Map<string, GeneratedOutput>()
  for (const output of outputs) {
    const first = outputByPath.get(output.outputPath)
    if (first) {
      throw new Error(`Generated output path ${output.outputPath} is claimed more than once.`)
    }
    outputByPath.set(output.outputPath, output)
  }

  const staged: StagedGeneratedOutput[] = []
  try {
    for (const output of [...outputByPath.values()].toSorted((left, right) =>
      left.outputPath.localeCompare(right.outputPath)
    )) {
      const previous = await existingContents(output.outputPath)
      if (previous === output.contents) {
        continue
      }

      await mkdir(dirname(output.outputPath), { recursive: true })
      const nonce = `${process.pid}-${randomUUID()}`
      const stagedPath = join(dirname(output.outputPath), `.${basename(output.outputPath)}.${nonce}.staged`)
      const backupPath = join(dirname(output.outputPath), `.${basename(output.outputPath)}.${nonce}.backup`)
      await writeFile(stagedPath, output.contents, { flag: 'wx' })
      staged.push({ ...output, backupPath, existed: previous !== null, stagedPath })
    }
  } catch (error) {
    await cleanStagingFiles(staged)
    throw error
  }

  const backedUp: StagedGeneratedOutput[] = []
  const installed: StagedGeneratedOutput[] = []
  try {
    for (const entry of staged) {
      if (entry.existed) {
        await rename(entry.outputPath, entry.backupPath)
        backedUp.push(entry)
      }
    }
    for (const entry of staged) {
      await rename(entry.stagedPath, entry.outputPath)
      installed.push(entry)
    }
  } catch (error) {
    const rollbackErrors = await rollbackGeneratedOutputs(installed, backedUp)
    await cleanStagingFiles(staged)
    if (rollbackErrors.length > 0) {
      throw new AggregateError(
        [error, ...rollbackErrors],
        'Generated output commit failed and rollback was incomplete.'
      )
    }
    throw error
  }

  await cleanStagingFiles(staged)
}

export interface GenerateTypedSqlResult {
  readonly generatedFiles: readonly string[]
  readonly removedFiles: number
  readonly statementCount: number
}

export async function generateTypedSql(config: PostgresTypedSqlConfig): Promise<GenerateTypedSqlResult> {
  if (generationInProgress) {
    throw new Error('Concurrent generation in one process is not supported.')
  }

  generationInProgress = true
  const resolvedConfig = resolveConfig(config)
  let database: Awaited<ReturnType<typeof createAnalysisDatabase>> | undefined

  try {
    database = await createAnalysisDatabase({
      extensions: resolvedConfig.extensions,
      schemaFiles: resolvedConfig.schemaFiles,
    })
    const catalogContents = await buildCatalogTypes(database, resolvedConfig)
    const rawConfigs = await readTypedSqlConfigs(resolvedConfig)
    assertUniqueTypedSqlNames(rawConfigs)
    const configs = rawConfigs.map(compileTypedSql)
    const resolvedConfigs = await resolveTypedSqlWithAnalyzer(configs, database, resolvedConfig)

    await commitGeneratedOutputs([
      { contents: catalogContents, outputPath: resolvedConfig.typesOutput },
      ...resolvedConfigs.map((entry) => ({
        contents: renderTypedSql(entry, resolvedConfig),
        outputPath: entry.outputPath,
      })),
    ])
    const removedFiles = await removeStaleGeneratedFiles(resolvedConfigs, resolvedConfig)
    return {
      generatedFiles: resolvedConfigs.map((entry) => entry.outputPath),
      removedFiles,
      statementCount: configs.length,
    }
  } finally {
    await database?.close()
    generationInProgress = false
  }
}
