import { randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { lstat, mkdir, readFile, readdir, realpath, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, relative } from 'node:path'

import { buildTypedSqlPostgresIrFromCompiledConfigs } from './analyzer-ir.js'
import {
  flattenJsonShapeAlternatives,
  resultNullabilityAllowsNull,
  type TypedSqlPostgresIrAccessConcern,
  type TypedSqlPostgresIrAccessEvidence,
  type TypedSqlPostgresIrCheckConstraintTypeExpression,
  type TypedSqlPostgresIrColumnSource,
  type TypedSqlPostgresIrJsonField,
  type TypedSqlPostgresIrJsonShape,
  type TypedSqlPostgresIrRowBounds,
} from './analyzer-ir-model.js'
import { buildCatalogTypes } from './catalog-generator.js'
import type { PostgresTypedSqlPropertyNaming, ResolvedPostgresTypedSqlConfig } from './config.js'
import { resolveConfig, type PostgresTypedSqlConfig } from './config.js'
import type { PostgresQueryable } from './database.js'
import { createAnalysisDatabase } from './engine.js'
import {
  postgresJsonSupportsStringLiteralRefinement,
  postgresParameterSupportsStringLiteralRefinement,
  postgresResultSupportsStringLiteralRefinement,
  resolveTypeScriptJsonScalarTypeForPostgresType,
  resolveTypeScriptParameterTypeForPostgresType,
  resolveTypeScriptResultTypeForPostgresType,
  type ResolvedPostgresCodecProfile,
  type PostgresTypeScriptResolution,
} from './postgres-codecs.js'
import { postgresJsonValueMayBeStructured } from './postgres-types.js'
import { compileNamedParameters, parseTypedSqlSource } from './sql-source.js'
import type { TypedSqlCardinality } from './runtime.js'
import {
  assertTypeScriptBindingIdentifier,
  assertUniqueTypeScriptBindings,
  camelCasePropertyName,
  pascalCaseIdentifier,
  quotePropertyName,
  renderTypeScriptLineCommentValue,
  type TypeScriptBinding,
} from './typescript-names.js'

let generationInProgress = false
const typedSqlSourceSuffix = '.typed.sql'
const typedSqlOutputSuffix = '.typed-sql.ts'
const legacyTypedSqlOutputSuffixes = ['.typed.sql.ts']
const generatedByMarker = 'This file is auto-generated by postgres-typed-sql'
const generatedMarkerLine = `// ${generatedByMarker}`
const ignoredDiscoveryDirectories = new Set([
  '.git',
  '.next',
  '.turbo',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'out',
  'playwright-report',
  'reports',
  'test-results',
])

interface SqlParameterDeclaration {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
}

interface SqlParameter extends SqlParameterDeclaration {
  readonly propertyName: string
}

interface SqlColumn {
  readonly name: string
  readonly nullable?: boolean
  readonly pgType?: string
}

interface TypedSqlConfig {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameterDeclaration[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface CompiledTypedSql {
  readonly access?: TypedSqlAccess
  readonly columns: readonly SqlColumn[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly SqlParameter[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface ResolvedSqlParameter {
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly tsType: string
}

interface ResolvedSqlColumn {
  readonly jsonMapping?: GeneratedJsonMapping
  readonly jsonShape?: ResolvedJsonShape
  readonly name: string
  readonly nullable: boolean
  readonly pgType: string
  readonly pgTypeName: string
  readonly pgTypeOid: number
  readonly pgTypeSchema: string
  readonly propertyName: string
  readonly source: TypedSqlPostgresIrColumnSource | null
  readonly tsType: string
}

type TypedSqlCommand = 'delete' | 'insert' | 'merge' | 'select' | 'unknown' | 'update'
type TypedSqlAccess = 'read' | 'write'

interface ResolvedTypedSql {
  readonly access: TypedSqlAccess
  readonly cardinality: TypedSqlCardinality
  readonly columns: readonly ResolvedSqlColumn[]
  readonly command: TypedSqlCommand
  readonly generatedTypeDeclarations: readonly string[]
  readonly name: string
  readonly outputPath: string
  readonly parameters: readonly ResolvedSqlParameter[]
  readonly rowBounds: TypedSqlPostgresIrRowBounds
  readonly scalarTypeImports: readonly string[]
  readonly sourceFile: string
  readonly sourcePath: string
  readonly sql: string
}

interface TypeScriptDependencies {
  readonly ambient: Set<string>
  readonly scalar: Set<string>
}

function requireSqlName(value: string, sourceFile: string): string {
  if (!/^[a-z][A-Za-z0-9]*$/u.test(value)) {
    throw new Error(`${sourceFile}: @name must be a lower camel-case identifier.`)
  }
  assertTypeScriptBindingIdentifier(value, `${sourceFile}: @name`)
  if (value === 'createTypedSqlStatement') {
    throw new Error(`${sourceFile}: @name createTypedSqlStatement collides with the generated runtime import.`)
  }

  return value
}

function lowerCamelCaseFromPathBase(base: string): string {
  const parts = base.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0)
  if (parts.length === 0) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const [head, ...tail] = parts
  if (!head) {
    throw new Error(`${base}: typed SQL filename must contain at least one identifier segment.`)
  }

  const identifier = [
    head.toLowerCase(),
    ...tail.map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1).toLowerCase()}`),
  ].join('')

  return requireSqlName(identifier, base)
}

function quoteString(value: string): string {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll('\t', '\\t')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')

  return value.includes("'") ? `"${escaped.replaceAll('"', '\\"')}"` : `'${escaped.replaceAll("'", "\\'")}'`
}

function relativePath(config: ResolvedPostgresTypedSqlConfig, filePath: string): string {
  return relative(config.rootDir, filePath)
}

function collectTypeResolutionDependencies(
  dependencies: TypeScriptDependencies,
  resolution: PostgresTypeScriptResolution
): void {
  for (const ambientBinding of resolution.ambientBindings) {
    dependencies.ambient.add(ambientBinding)
  }
  for (const scalarImport of resolution.scalarImports) {
    dependencies.scalar.add(scalarImport)
  }
}

function tsTypeForCheckConstraintType(type: TypedSqlPostgresIrCheckConstraintTypeExpression, nested = false): string {
  if (type.kind === 'literalUnion') {
    const rendered = type.labels.map(quoteString).join(' | ')
    return nested ? `(${rendered})` : rendered
  }

  const operator = type.kind === 'union' ? ' | ' : ' & '
  const rendered = type.members.map((member) => tsTypeForCheckConstraintType(member, true)).join(operator)
  return nested ? `(${rendered})` : rendered
}

function typedSqlCommandFromPostgres(command: string): TypedSqlCommand {
  switch (command.toLowerCase()) {
    case 'delete':
      return 'delete'
    case 'insert':
      return 'insert'
    case 'merge':
      return 'merge'
    case 'select':
      return 'select'
    case 'update':
      return 'update'
    default:
      return 'unknown'
  }
}

function typedSqlCardinalityFromRowBounds(bounds: TypedSqlPostgresIrRowBounds): TypedSqlCardinality {
  if (bounds.min === 0 && bounds.max === 0) {
    return 'none'
  }
  if (bounds.min === 1 && bounds.max === 1) {
    return 'one'
  }
  if (bounds.min === 0 && bounds.max === 1) {
    return 'optional'
  }
  return 'many'
}

function typedSqlAccessFromEvidence(evidence: TypedSqlPostgresIrAccessEvidence): TypedSqlAccess {
  return evidence.kind === 'provenReadOnly' ? 'read' : 'write'
}

function accessConcernDescription(concern: TypedSqlPostgresIrAccessConcern): string {
  switch (concern.kind) {
    case 'definiteDml':
      return `direct ${concern.command} DML`
    case 'dataModifyingCte':
      return 'a data-modifying CTE'
    case 'rowLock':
      return 'a row lock that is incompatible with read-only execution'
    case 'volatileExecution':
      return 'an execution-reachable volatile path that prevents a read-only proof'
    case 'procedureCall':
      return 'an opaque procedure call whose read-only behavior cannot be proved'
  }
}

function parseDirectivePgType(pgType: string | undefined): {
  readonly nullable: boolean
  readonly pgType?: string
} {
  if (!pgType) {
    return { nullable: false }
  }

  if (pgType === '?') {
    return { nullable: true }
  }

  if (pgType.endsWith('?')) {
    const typeWithoutSuffix = pgType.slice(0, -1).trimEnd()
    return { nullable: true, ...(typeWithoutSuffix ? { pgType: typeWithoutSuffix } : {}) }
  }

  return { nullable: false, pgType }
}

async function walkTypedSqlFiles(directory: string, output: string[]): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true })
  for (const entry of entries) {
    const entryPath = join(directory, entry.name)
    if (entry.isDirectory()) {
      if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
        await walkTypedSqlFiles(entryPath, output)
      }
      continue
    }

    if (entry.isFile() && entry.name.endsWith(typedSqlSourceSuffix)) {
      output.push(entryPath)
    }
  }
}

async function findTypedSqlSourceFiles(config: ResolvedPostgresTypedSqlConfig): Promise<string[]> {
  const sourceFiles = new Map<string, string>()
  const includeRoots = new Map<string, string>()
  for (const includeRoot of config.include) {
    const canonical = await realpath(includeRoot)
    if (!includeRoots.has(canonical)) {
      includeRoots.set(canonical, includeRoot)
    }
  }
  for (const includeRoot of includeRoots.values()) {
    const entries: string[] = []
    await walkTypedSqlFiles(includeRoot, entries)
    for (const entry of entries) {
      const canonical = await realpath(entry)
      if (!sourceFiles.has(canonical)) {
        sourceFiles.set(canonical, entry)
      }
    }
  }
  return [...sourceFiles.values()].toSorted((left, right) =>
    relativePath(config, left).localeCompare(relativePath(config, right))
  )
}

function generatedOutputPath(sourcePath: string): string {
  return `${sourcePath.slice(0, -typedSqlSourceSuffix.length)}${typedSqlOutputSuffix}`
}

async function readTypedSqlConfigs(generatorConfig: ResolvedPostgresTypedSqlConfig): Promise<TypedSqlConfig[]> {
  const sourcePaths = await findTypedSqlSourceFiles(generatorConfig)
  const configs: TypedSqlConfig[] = []

  for (const sourcePath of sourcePaths) {
    const sourceFile = relativePath(generatorConfig, sourcePath)
    const text = readFileSync(sourcePath, 'utf8')
    const parsedSource = parseTypedSqlSource(text, sourceFile)
    const defaultName = lowerCamelCaseFromPathBase(basename(sourceFile, typedSqlSourceSuffix))
    let access: TypedSqlAccess | undefined
    let name = defaultName
    const parameters: SqlParameterDeclaration[] = []
    const columns: SqlColumn[] = []
    let firstAccessLocation: string | undefined
    let firstNameLocation: string | undefined
    const firstColumnDirectiveByName = new Map<string, string>()
    const firstParameterDirectiveByName = new Map<string, string>()

    for (const directive of parsedSource.directives) {
      const location = `${sourceFile}:${directive.line}`
      const kind = directive.kind
      const bodyParts = /^(\S+)(?:\s+([\s\S]*))?$/u.exec(directive.body)
      const identifier = bodyParts?.[1]
      const rawPgType = bodyParts?.[2]?.trim()
      const parsedPgType = parseDirectivePgType(rawPgType)
      const pgType = parsedPgType.pgType
      if (kind === 'name') {
        if (!identifier || rawPgType) {
          throw new Error(`${location}: @name requires exactly one identifier.`)
        }

        if (firstNameLocation) {
          throw new Error(`${location}: duplicate @name; first declared at ${firstNameLocation}.`)
        }
        firstNameLocation = location
        name = requireSqlName(identifier, location)
        continue
      }

      if (kind === 'access') {
        if ((identifier !== 'read' && identifier !== 'write') || rawPgType) {
          throw new Error(`${location}: @access requires exactly read or write.`)
        }

        if (firstAccessLocation) {
          throw new Error(`${location}: duplicate @access; first declared at ${firstAccessLocation}.`)
        }
        firstAccessLocation = location
        access = identifier
        continue
      }

      if (kind !== 'param' && kind !== 'column') {
        throw new Error(`${location}: unsupported typed SQL directive @${kind}.`)
      }

      if (!identifier) {
        throw new Error(`${location}: @${kind} requires a name.`)
      }
      if (kind === 'param' && !/^[A-Za-z_][A-Za-z0-9_]*$/u.test(identifier)) {
        throw new Error(`${location}: @param requires a named-parameter identifier.`)
      }
      if (kind === 'column' && parsedPgType.nullable) {
        throw new Error(`${location}: @column does not support ?; PostgreSQL determines result nullability.`)
      }

      const firstDirectiveByName = kind === 'param' ? firstParameterDirectiveByName : firstColumnDirectiveByName
      const firstLocation = firstDirectiveByName.get(identifier)
      if (firstLocation) {
        throw new Error(`${location}: duplicate @${kind} ${identifier}; first declared at ${firstLocation}.`)
      }
      firstDirectiveByName.set(identifier, location)

      const entry = {
        name: identifier,
        nullable: parsedPgType.nullable,
        pgType,
      }

      if (kind === 'param') {
        parameters.push(entry)
      } else {
        columns.push(entry)
      }
    }

    configs.push({
      access,
      columns,
      name,
      outputPath: generatedOutputPath(sourcePath),
      parameters,
      sourceFile,
      sourcePath,
      sql: parsedSource.sql,
    })
  }

  return configs
}

function assertUniqueTypedSqlNames(configs: readonly TypedSqlConfig[]): void {
  const firstSourceByName = new Map<string, string>()
  for (const config of configs) {
    const firstSource = firstSourceByName.get(config.name)
    if (firstSource) {
      throw new Error(`${config.sourceFile}: typed SQL statement name ${config.name} already used by ${firstSource}.`)
    }
    firstSourceByName.set(config.name, config.sourceFile)
  }
}

function compileTypedSql(config: TypedSqlConfig, parameterNaming: PostgresTypedSqlPropertyNaming): CompiledTypedSql {
  const parametersByName = new Map(config.parameters.map((parameter) => [parameter.name, parameter]))
  const compiled = compileNamedParameters(config.sql, config.sourceFile)
  const parameters = compiled.parameterNames.map((name): SqlParameter => {
    const declaration = parametersByName.get(name) ?? { name }
    return {
      ...declaration,
      propertyName: propertyNameForNaming(name, parameterNaming),
    }
  })
  assertUniquePublicNames(
    parameters.map((parameter) => parameter.propertyName),
    'parameter property',
    config.sourceFile
  )

  const unusedParameters = config.parameters.filter(
    (parameter) => !parameters.some((used) => used.name === parameter.name)
  )
  if (unusedParameters.length > 0) {
    throw new Error(
      `${config.sourceFile}: declared parameter(s) not used: ${unusedParameters.map((parameter) => parameter.name).join(', ')}.`
    )
  }

  return {
    access: config.access,
    columns: config.columns,
    name: config.name,
    outputPath: config.outputPath,
    parameters,
    sourceFile: config.sourceFile,
    sourcePath: config.sourcePath,
    sql: compiled.sql,
  }
}

interface GeneratedJsonTypeDeclaration {
  readonly fields: readonly {
    readonly nullable: boolean
    readonly propertyName: string
    readonly tsType: string
  }[]
  readonly name: string
}

type ResolvedJsonLeafShape<Kind extends 'opaque' | 'scalar' | 'stringLiteral'> = Omit<
  Extract<TypedSqlPostgresIrJsonShape, { readonly kind: Kind }>,
  'nullability'
> & {
  readonly nullable: boolean
}

type ResolvedJsonShape =
  | {
      readonly element: ResolvedJsonShape
      readonly kind: 'array'
      readonly nullable: boolean
    }
  | {
      readonly fields: readonly ResolvedJsonField[]
      readonly kind: 'object'
      readonly nullable: boolean
    }
  | ResolvedJsonLeafShape<'opaque'>
  | ResolvedJsonLeafShape<'scalar'>
  | ResolvedJsonLeafShape<'stringLiteral'>
  | {
      readonly alternatives: readonly ResolvedJsonShape[]
      readonly kind: 'union'
      readonly nullable: boolean
    }

interface ResolvedJsonField {
  readonly name: string
  readonly propertyName: string
  readonly shape: ResolvedJsonShape
}

interface GeneratedJsonFieldMapping {
  readonly mapping?: GeneratedJsonMapping
  readonly name: string
  readonly propertyName: string
}

interface GeneratedJsonMapping {
  readonly arrayElement?: GeneratedJsonMapping
  readonly fields?: readonly GeneratedJsonFieldMapping[]
}

function propertyNameForNaming(name: string, naming: PostgresTypedSqlPropertyNaming): string {
  return naming === 'camelCase' ? camelCasePropertyName(name) : name
}

function resolveJsonShapeNames(
  shape: TypedSqlPostgresIrJsonShape,
  naming: PostgresTypedSqlPropertyNaming,
  sourceFile: string,
  context: string
): ResolvedJsonShape {
  switch (shape.kind) {
    case 'array':
      return {
        element: resolveJsonShapeNames(shape.element, naming, sourceFile, `${context}[]`),
        kind: 'array',
        nullable: resultNullabilityAllowsNull(shape.nullability),
      }
    case 'object': {
      const fields = shape.fields.map((field) => ({
        name: field.name,
        propertyName: propertyNameForNaming(field.name, naming),
        shape: resolveJsonShapeNames(field.shape, naming, sourceFile, `${context}.${field.name}`),
      }))
      assertUniquePublicNames(
        fields.map((field) => field.propertyName),
        `JSON field in ${context}`,
        sourceFile
      )
      return {
        fields,
        kind: 'object',
        nullable: resultNullabilityAllowsNull(shape.nullability),
      }
    }
    case 'opaque':
    case 'scalar':
    case 'stringLiteral': {
      const { nullability, ...value } = shape
      return {
        ...value,
        nullable: resultNullabilityAllowsNull(nullability),
      }
    }
    case 'union':
      return {
        alternatives: shape.alternatives.map((alternative, index) =>
          resolveJsonShapeNames(alternative, naming, sourceFile, `${context}<alternative ${index + 1}>`)
        ),
        kind: 'union',
        nullable: resultNullabilityAllowsNull(shape.nullability),
      }
  }
}

function isJsonTraversalBarrier(shape: TypedSqlPostgresIrJsonShape): boolean {
  return shape.kind === 'opaque' || (shape.kind === 'scalar' && postgresJsonValueMayBeStructured(shape))
}

function applyOpaqueJsonBarriersToAlternatives(
  shapes: readonly TypedSqlPostgresIrJsonShape[]
): readonly TypedSqlPostgresIrJsonShape[] {
  if (shapes.length === 0) {
    return shapes
  }
  const alternatives = shapes.flatMap(flattenJsonShapeAlternatives)
  if (alternatives.some(isJsonTraversalBarrier)) {
    return shapes.map((shape) => ({ kind: 'opaque', nullability: shape.nullability }))
  }

  const arrayElements = alternatives.flatMap((alternative) =>
    alternative.kind === 'array' ? [alternative.element] : []
  )
  const safeArrayElements = applyOpaqueJsonBarriersToAlternatives(arrayElements)
  let arrayIndex = 0

  const objectFields = new Map<string, TypedSqlPostgresIrJsonField[]>()
  for (const alternative of alternatives) {
    if (alternative.kind !== 'object') {
      continue
    }
    for (const field of alternative.fields) {
      const fields = objectFields.get(field.name) ?? []
      fields.push(field)
      objectFields.set(field.name, fields)
    }
  }
  const safeObjectFieldShapes = new Map(
    [...objectFields].map(([name, fields]) => [
      name,
      applyOpaqueJsonBarriersToAlternatives(fields.map((field) => field.shape)),
    ])
  )
  const objectFieldIndexes = new Map<string, number>()

  const rewrite = (shape: TypedSqlPostgresIrJsonShape): TypedSqlPostgresIrJsonShape => {
    switch (shape.kind) {
      case 'array': {
        const element = safeArrayElements[arrayIndex]
        arrayIndex += 1
        return { ...shape, element: element ?? shape.element }
      }
      case 'object':
        return {
          ...shape,
          fields: shape.fields.map((field) => {
            const fieldIndex = objectFieldIndexes.get(field.name) ?? 0
            objectFieldIndexes.set(field.name, fieldIndex + 1)
            return {
              ...field,
              shape: safeObjectFieldShapes.get(field.name)?.[fieldIndex] ?? field.shape,
            }
          }),
        }
      case 'union':
        return { ...shape, alternatives: shape.alternatives.map(rewrite) }
      case 'opaque':
      case 'scalar':
      case 'stringLiteral':
        return shape
    }
  }

  return shapes.map(rewrite)
}

function applyOpaqueJsonBarriers(shape: TypedSqlPostgresIrJsonShape): TypedSqlPostgresIrJsonShape {
  return applyOpaqueJsonBarriersToAlternatives([shape])[0] ?? shape
}

function flattenResolvedJsonAlternatives(shape: ResolvedJsonShape): readonly ResolvedJsonShape[] {
  return shape.kind === 'union' ? shape.alternatives.flatMap(flattenResolvedJsonAlternatives) : [shape]
}

function jsonMappingForAlternatives(shapes: readonly ResolvedJsonShape[]): GeneratedJsonMapping | undefined {
  const alternatives = shapes.flatMap(flattenResolvedJsonAlternatives)
  if (alternatives.some((alternative) => alternative.kind === 'opaque')) {
    return undefined
  }

  const elementShapes = alternatives.flatMap((alternative) =>
    alternative.kind === 'array' ? [alternative.element] : []
  )
  const arrayElement = elementShapes.length > 0 ? jsonMappingForAlternatives(elementShapes) : undefined

  const fieldsByName = new Map<string, { propertyName: string; shapes: ResolvedJsonShape[] }>()
  for (const alternative of alternatives) {
    if (alternative.kind !== 'object') {
      continue
    }
    for (const field of alternative.fields) {
      const existing = fieldsByName.get(field.name)
      if (existing) {
        if (existing.propertyName !== field.propertyName) {
          throw new Error(`Inconsistent mapped property name for JSON field ${JSON.stringify(field.name)}.`)
        }
        existing.shapes.push(field.shape)
      } else {
        fieldsByName.set(field.name, { propertyName: field.propertyName, shapes: [field.shape] })
      }
    }
  }
  const fields = [...fieldsByName].flatMap(
    ([name, { propertyName, shapes: fieldShapes }]): GeneratedJsonFieldMapping[] => {
      const mapping = jsonMappingForAlternatives(fieldShapes)
      return propertyName !== name || mapping
        ? [
            {
              ...(mapping ? { mapping } : {}),
              name,
              propertyName,
            },
          ]
        : []
    }
  )
  return arrayElement || fields.length > 0
    ? {
        ...(arrayElement ? { arrayElement } : {}),
        ...(fields.length > 0 ? { fields } : {}),
      }
    : undefined
}

function jsonMappingForShape(shape: ResolvedJsonShape): GeneratedJsonMapping | undefined {
  return jsonMappingForAlternatives([shape])
}

function assertUniquePublicNames(names: readonly string[], kind: string, sourceFile: string): void {
  const firstIndexByName = new Map<string, number>()
  for (const [index, name] of names.entries()) {
    const firstIndex = firstIndexByName.get(name)
    if (firstIndex !== undefined) {
      throw new Error(
        `${sourceFile}: duplicate ${kind} name ${JSON.stringify(name)} at positions ${firstIndex + 1} and ${index + 1}.`
      )
    }
    firstIndexByName.set(name, index)
  }
}

function reserveGeneratedTypeBinding(
  bindings: Map<string, string>,
  name: string,
  source: string,
  sourceFile: string
): void {
  assertTypeScriptBindingIdentifier(name, `${sourceFile}: generated type for ${source}`)
  const firstSource = bindings.get(name)
  if (firstSource) {
    throw new Error(
      `${sourceFile}: generated TypeScript binding ${name} for ${source} collides with ${firstSource}. Alias the SQL field to give it a distinct name.`
    )
  }
  bindings.set(name, source)
}

function encodedTypeNameSegment(value: string): string {
  let encoded = ''
  for (const character of value) {
    encoded += /^[A-Za-z0-9_]$/u.test(character) ? character : `$${character.codePointAt(0)?.toString(16) ?? ''}$`
  }
  return `J${encoded.length}_${encoded}`
}

function scalarTsTypeForJsonShape(
  shape: Extract<ResolvedJsonShape, { readonly kind: 'scalar' }>,
  dependencies: TypeScriptDependencies,
  codecProfile: ResolvedPostgresCodecProfile
): string {
  if (shape.checkConstraintType && postgresJsonSupportsStringLiteralRefinement(shape, codecProfile)) {
    return tsTypeForCheckConstraintType(shape.checkConstraintType)
  }

  const resolved = resolveTypeScriptJsonScalarTypeForPostgresType(shape, codecProfile)
  collectTypeResolutionDependencies(dependencies, resolved)
  return resolved.type
}

function tsTypeForJsonShape(
  shape: ResolvedJsonShape,
  sourceFile: string,
  suggestedName: string,
  declarations: GeneratedJsonTypeDeclaration[],
  usedNames: Map<string, string>,
  dependencies: TypeScriptDependencies,
  codecProfile: ResolvedPostgresCodecProfile
): string {
  switch (shape.kind) {
    case 'array':
      return `readonly (${tsTypeForJsonShape(
        shape.element,
        sourceFile,
        `${suggestedName}${encodedTypeNameSegment('element')}`,
        declarations,
        usedNames,
        dependencies,
        codecProfile
      )}${shape.element.nullable ? ' | null' : ''})[]`
    case 'object': {
      reserveGeneratedTypeBinding(usedNames, suggestedName, `JSON object ${suggestedName}`, sourceFile)
      assertUniquePublicNames(
        shape.fields.map((field) => field.propertyName),
        `JSON field in ${suggestedName}`,
        sourceFile
      )
      const name = suggestedName
      declarations.push({
        fields: shape.fields.map((field) => ({
          nullable: field.shape.nullable,
          propertyName: field.propertyName,
          tsType: tsTypeForJsonShape(
            field.shape,
            sourceFile,
            `${name}${encodedTypeNameSegment(field.name)}`,
            declarations,
            usedNames,
            dependencies,
            codecProfile
          ),
        })),
        name,
      })
      return name
    }
    case 'opaque':
      collectTypeResolutionDependencies(dependencies, codecProfile.opaqueJsonType)
      return codecProfile.opaqueJsonType.type
    case 'union':
      return shape.alternatives
        .map((alternative, index) =>
          tsTypeForJsonShape(
            alternative,
            sourceFile,
            `${suggestedName}${encodedTypeNameSegment(`alternative${index + 1}`)}`,
            declarations,
            usedNames,
            dependencies,
            codecProfile
          )
        )
        .join(' | ')
    case 'scalar':
      return scalarTsTypeForJsonShape(shape, dependencies, codecProfile)
    case 'stringLiteral': {
      if (postgresJsonSupportsStringLiteralRefinement(shape, codecProfile)) {
        return quoteString(shape.value)
      }
      const resolved = resolveTypeScriptJsonScalarTypeForPostgresType(shape, codecProfile)
      collectTypeResolutionDependencies(dependencies, resolved)
      return resolved.type
    }
  }
}

function renderImports(configs: readonly ResolvedTypedSql[], generatorConfig: ResolvedPostgresTypedSqlConfig): string {
  const scalarImports = new Set<string>()
  for (const config of configs) {
    for (const identifier of config.scalarTypeImports) {
      scalarImports.add(identifier)
    }
  }

  const lines: string[] = []
  if (scalarImports.size > 0) {
    lines.push(
      `import type { ${[...scalarImports].toSorted().join(', ')} } from ${quoteString(generatorConfig.imports.scalars)}`
    )
  }
  lines.push(`import { createTypedSqlStatement } from ${quoteString(generatorConfig.imports.runtime)}`)

  return lines.join('\n')
}

function renderInterface(
  name: string,
  fields: readonly (
    | Pick<ResolvedSqlColumn, 'nullable' | 'propertyName' | 'tsType'>
    | Pick<ResolvedSqlParameter, 'nullable' | 'propertyName' | 'tsType'>
  )[]
): string {
  if (fields.length === 0) {
    return `export type ${name} = Record<string, never>`
  }

  return [
    `export interface ${name} {`,
    ...fields.map(
      (field) =>
        `  readonly ${quotePropertyName(field.propertyName)}: ${field.tsType}${'nullable' in field && field.nullable ? ' | null' : ''}`
    ),
    '}',
  ].join('\n')
}

function renderGeneratedTypeDeclaration(declaration: GeneratedJsonTypeDeclaration): string {
  return renderInterface(declaration.name, declaration.fields)
}

function renderColumnSourceMetadata(source: TypedSqlPostgresIrColumnSource): string {
  if (source.kind !== 'tableColumn') {
    return JSON.stringify(source)
  }

  const stableSource = {
    attname: source.attname,
    kind: source.kind,
    relname: source.relname,
    varlevelsup: source.varlevelsup,
    varno: source.varno,
    varnullingrels: source.varnullingrels,
  }
  return JSON.stringify(stableSource)
}

function renderColumnMetadata(columns: readonly ResolvedSqlColumn[]): string {
  if (columns.length === 0) {
    return '[]'
  }

  return `[
${columns
  .map(
    (column) => `    {
      ${column.jsonMapping ? `jsonMapping: ${JSON.stringify(column.jsonMapping)},\n      ` : ''}name: ${quoteString(column.name)},
      nullable: ${column.nullable},
      pgType: ${quoteString(column.pgType)},
      pgTypeName: ${quoteString(column.pgTypeName)},
      pgTypeSchema: ${quoteString(column.pgTypeSchema)},
      propertyName: ${quoteString(column.propertyName)}${
        column.source ? `,\n      source: ${renderColumnSourceMetadata(column.source)}` : ''
      },
    }`
  )
  .join(',\n')},
  ]`
}

function renderParameterMetadata(parameters: readonly ResolvedSqlParameter[]): string {
  if (parameters.length === 0) {
    return '[]'
  }

  return `[
${parameters
  .map(
    (parameter) => `    {
      name: ${quoteString(parameter.name)},
      nullable: ${parameter.nullable},
      pgType: ${quoteString(parameter.pgType)},
      pgTypeName: ${quoteString(parameter.pgTypeName)},
      pgTypeSchema: ${quoteString(parameter.pgTypeSchema)},
      propertyName: ${quoteString(parameter.propertyName)},
    }`
  )
  .join(',\n')},
  ]`
}

function renderStatement(config: ResolvedTypedSql): string {
  const paramsName = `${pascalCaseIdentifier(config.name)}Params`
  const rowName = `${pascalCaseIdentifier(config.name)}Row`
  const parameterNames = config.parameters.map((parameter) => quoteString(parameter.propertyName)).join(', ')
  const generatedTypeDeclarations =
    config.generatedTypeDeclarations.length > 0 ? `${config.generatedTypeDeclarations.join('\n\n')}\n\n` : ''

  return `${generatedTypeDeclarations}${renderInterface(paramsName, config.parameters)}

${renderInterface(rowName, config.columns)}

export const ${config.name} = createTypedSqlStatement<
  ${paramsName},
  ${rowName},
  ${quoteString(config.access)},
  ${quoteString(config.cardinality)}
>({
  access: ${quoteString(config.access)},
  columns: ${renderColumnMetadata(config.columns)},
  command: ${quoteString(config.command)},
  cardinality: ${quoteString(config.cardinality)},
  name: ${quoteString(config.name)},
  parameterNames: [${parameterNames}],
  parameters: ${renderParameterMetadata(config.parameters)},
  rowBounds: { min: ${config.rowBounds.min}, max: ${config.rowBounds.max ?? 'null'}, proof: ${quoteString(config.rowBounds.proof)} },
  text: ${quoteString(config.sql)},
})`
}

function renderTypedSql(config: ResolvedTypedSql, generatorConfig: ResolvedPostgresTypedSqlConfig): string {
  const sourcePath = renderTypeScriptLineCommentValue(`./${basename(config.sourcePath)}`)
  const codecProfileName = renderTypeScriptLineCommentValue(generatorConfig.codecProfile.name)
  return `// ${generatedByMarker}
// Source: ${sourcePath}
// Codec profile: ${codecProfileName}
// DO NOT EDIT MANUALLY

${renderImports([config], generatorConfig)}

${renderStatement(config)}
`
}

async function assertColumnAssertions(
  client: PostgresQueryable,
  config: CompiledTypedSql,
  resolvedColumns: readonly ResolvedSqlColumn[]
): Promise<void> {
  if (config.columns.length === 0) {
    return
  }

  const resolvedByName = new Map(resolvedColumns.map((column) => [column.name, column]))
  const typedAssertions: { readonly assertion: SqlColumn; readonly resolved: ResolvedSqlColumn }[] = []
  for (const assertion of config.columns) {
    const resolved = resolvedByName.get(assertion.name)
    if (!resolved) {
      throw new Error(`${config.sourceFile}: @column ${assertion.name} does not exist in the PostgreSQL result.`)
    }

    if (assertion.pgType) {
      typedAssertions.push({ assertion, resolved })
    }
  }

  if (typedAssertions.length === 0) {
    return
  }

  const result = await client.query<{ readonly oid: number | null; readonly ordinal: number }>(
    `
      select
        asserted.ordinality::int as ordinal,
        to_regtype(asserted.pg_type)::oid::int as oid
      from unnest($1::text[]) with ordinality as asserted(pg_type, ordinality)
    `,
    [typedAssertions.map(({ assertion }) => assertion.pgType)]
  )
  const oidByOrdinal = new Map(result.rows.map((row) => [row.ordinal, row.oid]))
  for (const [index, { assertion, resolved }] of typedAssertions.entries()) {
    const assertedOid = oidByOrdinal.get(index + 1)
    if (!assertedOid) {
      throw new Error(`${config.sourceFile}: unknown @column type ${assertion.pgType} for ${assertion.name}.`)
    }
    if (assertedOid !== resolved.pgTypeOid) {
      throw new Error(
        `${config.sourceFile}: result column ${assertion.name} type drift. Expected ${assertion.pgType}, PostgreSQL inferred ${resolved.pgType}.`
      )
    }
  }
}

async function resolveTypedSqlWithAnalyzer(
  configs: readonly CompiledTypedSql[],
  client: PostgresQueryable,
  generatorConfig: ResolvedPostgresTypedSqlConfig
): Promise<ResolvedTypedSql[]> {
  const result = await buildTypedSqlPostgresIrFromCompiledConfigs(
    client,
    configs.map((config) => ({
      name: config.name,
      parameterNames: config.parameters.map((parameter) => parameter.name),
      parameterTypes: config.parameters.map((parameter) => parameter.pgType),
      sourceFile: config.sourceFile,
      sql: config.sql,
    }))
  )

  const resolvedQueries: ResolvedTypedSql[] = []
  for (const [index, ir] of result.queries.entries()) {
    const config = configs[index]
    if (!config) {
      throw new Error(`PostgreSQL analyzer returned an unexpected extra query ${ir.name}.`)
    }

    const generatedDeclarations: GeneratedJsonTypeDeclaration[] = []
    const typeDependencies: TypeScriptDependencies = {
      ambient: new Set(),
      scalar: new Set(),
    }
    const statementTypeBindings: TypeScriptBinding[] = [
      { name: `${pascalCaseIdentifier(config.name)}Params`, source: 'parameter interface' },
      { name: `${pascalCaseIdentifier(config.name)}Row`, source: 'row interface' },
    ]
    assertUniqueTypeScriptBindings(statementTypeBindings, config.sourceFile)
    const usedGeneratedTypeNames = new Map(statementTypeBindings.map((binding) => [binding.name, binding.source]))
    const columns = ir.resultColumns.map((column, columnIndex): ResolvedSqlColumn => {
      const name = column.name ?? `column_${columnIndex + 1}`
      const propertyName = propertyNameForNaming(name, generatorConfig.naming.resultColumns)
      const suggestedJsonTypeName = `${pascalCaseIdentifier(config.name)}${encodedTypeNameSegment(name)}Json`
      const safeJsonShape = column.jsonShape ? applyOpaqueJsonBarriers(column.jsonShape) : undefined
      const resolvedJsonShape = safeJsonShape
        ? resolveJsonShapeNames(
            safeJsonShape,
            generatorConfig.naming.structuredJsonFields,
            config.sourceFile,
            `result column ${JSON.stringify(name)}`
          )
        : undefined
      const jsonMapping = resolvedJsonShape ? jsonMappingForShape(resolvedJsonShape) : undefined
      if (jsonMapping && !generatorConfig.codecProfile.structuredJson) {
        throw new Error(
          `${config.sourceFile}: structured JSON field naming for result column ${JSON.stringify(name)} requires a codec profile that decodes structured JSON.`
        )
      }
      const jsonShape = generatorConfig.codecProfile.structuredJson ? resolvedJsonShape : undefined
      let tsType: string
      if (jsonShape) {
        tsType = tsTypeForJsonShape(
          jsonShape,
          config.sourceFile,
          suggestedJsonTypeName,
          generatedDeclarations,
          usedGeneratedTypeNames,
          typeDependencies,
          generatorConfig.codecProfile
        )
      } else {
        if (
          column.checkConstraintType &&
          postgresResultSupportsStringLiteralRefinement(column, generatorConfig.codecProfile)
        ) {
          tsType = tsTypeForCheckConstraintType(column.checkConstraintType)
        } else {
          const resolution = resolveTypeScriptResultTypeForPostgresType(column, generatorConfig.codecProfile)
          collectTypeResolutionDependencies(typeDependencies, resolution)
          tsType = resolution.type
        }
      }
      return {
        ...(jsonShape ? { jsonShape } : {}),
        ...(jsonMapping ? { jsonMapping } : {}),
        name,
        nullable: resultNullabilityAllowsNull(column.nullability),
        pgType: column.pgType,
        pgTypeName: column.pgTypeName,
        pgTypeOid: column.pgTypeOid,
        pgTypeSchema: column.pgTypeSchema,
        propertyName,
        source: column.source,
        tsType,
      }
    })
    assertUniquePublicNames(
      columns.map((column) => column.propertyName),
      'result column',
      config.sourceFile
    )
    await assertColumnAssertions(client, config, columns)
    const parameters = config.parameters.map((parameter, paramIndex): ResolvedSqlParameter => {
      const analyzed = ir.params[paramIndex]
      if (!analyzed) {
        throw new Error(`${config.sourceFile}: analyzer returned no type for parameter ${parameter.name}.`)
      }

      const resolution =
        analyzed.checkConstraintType &&
        postgresParameterSupportsStringLiteralRefinement(analyzed, generatorConfig.codecProfile)
          ? {
              ambientBindings: [],
              scalarImports: [],
              type: tsTypeForCheckConstraintType(analyzed.checkConstraintType),
            }
          : resolveTypeScriptParameterTypeForPostgresType(analyzed, generatorConfig.codecProfile)
      collectTypeResolutionDependencies(typeDependencies, resolution)
      if (parameter.nullable === true && analyzed.nullAdmission === 'rejects') {
        throw new Error(
          `${config.sourceFile}: @param ${parameter.name} cannot be nullable because PostgreSQL proves that one of its uses rejects NULL.`
        )
      }
      return {
        name: parameter.name,
        nullable: analyzed.nullAdmission === 'accepts' || parameter.nullable === true,
        pgType: analyzed.pgType,
        pgTypeName: analyzed.pgTypeName,
        pgTypeSchema: analyzed.pgTypeSchema,
        propertyName: parameter.propertyName,
        tsType: resolution.type,
      }
    })
    const usesRecordUtilityType =
      parameters.length === 0 || columns.length === 0 || generatedDeclarations.some(({ fields }) => fields.length === 0)
    const ambientBindings = new Set(typeDependencies.ambient)
    if (usesRecordUtilityType) {
      ambientBindings.add('Record')
    }
    assertUniqueTypeScriptBindings(
      [
        { name: 'createTypedSqlStatement', source: 'generated runtime import' },
        { name: config.name, source: 'exported statement constant' },
        ...[...usedGeneratedTypeNames].map(([name, source]) => ({ name, source })),
        ...[...ambientBindings].map((name) => ({ name, source: 'ambient TypeScript type' })),
        ...[...typeDependencies.scalar].map((name) => ({
          name,
          source: 'postgres-typed-sql scalar type import',
        })),
      ],
      config.sourceFile
    )

    const inferredAccess = typedSqlAccessFromEvidence(ir.accessEvidence)
    if (config.access === 'read' && inferredAccess === 'write') {
      const reasons =
        ir.accessEvidence.kind === 'notProvenReadOnly'
          ? ir.accessEvidence.reasons.map(accessConcernDescription).join('; ')
          : 'an unknown analyzer result'
      throw new Error(
        `${config.sourceFile}: @access read requires analyzer-proved read-only execution; PostgreSQL analysis found ${reasons}.`
      )
    }

    resolvedQueries.push({
      columns,
      access: config.access ?? inferredAccess,
      cardinality: typedSqlCardinalityFromRowBounds(ir.rowBounds),
      command: typedSqlCommandFromPostgres(ir.command),
      generatedTypeDeclarations: generatedDeclarations.map(renderGeneratedTypeDeclaration),
      name: config.name,
      outputPath: config.outputPath,
      parameters,
      rowBounds: ir.rowBounds,
      scalarTypeImports: [...typeDependencies.scalar].toSorted(),
      sourceFile: config.sourceFile,
      sourcePath: config.sourcePath,
      sql: config.sql,
    })
  }

  return resolvedQueries
}

async function findGeneratedTypedSqlFiles(config: ResolvedPostgresTypedSqlConfig): Promise<string[]> {
  const generatedFiles = new Map<string, string>()
  async function walk(directory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true })
    for (const entry of entries) {
      const entryPath = join(directory, entry.name)
      if (entry.isDirectory()) {
        if (!ignoredDiscoveryDirectories.has(entry.name) && !entry.name.startsWith('.')) {
          await walk(entryPath)
        }
        continue
      }

      if (
        entry.isFile() &&
        (entry.name.endsWith(typedSqlOutputSuffix) ||
          legacyTypedSqlOutputSuffixes.some((suffix) => entry.name.endsWith(suffix)))
      ) {
        const canonical = await realpath(entryPath)
        if (!generatedFiles.has(canonical)) {
          generatedFiles.set(canonical, entryPath)
        }
      }
    }
  }

  const includeRoots = new Map<string, string>()
  for (const includeRoot of config.include) {
    const canonical = await realpath(includeRoot)
    if (!includeRoots.has(canonical)) {
      includeRoots.set(canonical, includeRoot)
    }
  }
  for (const includeRoot of includeRoots.values()) {
    await walk(includeRoot)
  }
  return [...generatedFiles.values()].toSorted()
}

async function findStaleGeneratedFiles(
  configs: readonly ResolvedTypedSql[],
  generatorConfig: ResolvedPostgresTypedSqlConfig
): Promise<readonly string[]> {
  const expectedOutputPaths = new Set(
    await Promise.all(
      [generatorConfig.typesOutput, ...configs.map((config) => config.outputPath)].map(filesystemPathIdentity)
    )
  )
  const stale: string[] = []
  for (const generatedPath of await findGeneratedTypedSqlFiles(generatorConfig)) {
    if (expectedOutputPaths.has(await filesystemPathIdentity(generatedPath))) {
      continue
    }

    const contents = await readFile(generatedPath, 'utf8')
    if (
      contents !== generatedMarkerLine &&
      !contents.startsWith(`${generatedMarkerLine}\n`) &&
      !contents.startsWith(`${generatedMarkerLine}\r\n`)
    ) {
      continue
    }

    stale.push(generatedPath)
  }
  return stale
}

interface GeneratedOutput {
  readonly contents: string
  readonly outputPath: string
}

interface StagedGeneratedOutput extends GeneratedOutput {
  readonly backupPath: string
  readonly existed: boolean
  readonly stagedPath: string
}

interface StagedGeneratedDeletion {
  readonly backupPath: string
  readonly outputPath: string
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT'
}

function isAlreadyExistsError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'EEXIST'
}

async function existingContents(outputPath: string): Promise<string | null> {
  try {
    return await readFile(outputPath, 'utf8')
  } catch (error) {
    if (isMissingFileError(error)) {
      return null
    }
    throw error
  }
}

async function assertOutputIsNotSymbolicLink(outputPath: string): Promise<void> {
  try {
    const output = await lstat(outputPath)
    if (output.isSymbolicLink()) {
      throw new Error(`Generated output path ${outputPath} must not be a symbolic link.`)
    }
  } catch (error) {
    if (!isMissingFileError(error)) {
      throw error
    }
  }
}

async function canonicalFilesystemPath(path: string): Promise<string> {
  const missingSegments: string[] = []
  let existingAncestor = path

  while (true) {
    try {
      return join(await realpath(existingAncestor), ...missingSegments)
    } catch (error) {
      if (!isMissingFileError(error)) {
        throw error
      }
      const parent = dirname(existingAncestor)
      if (parent === existingAncestor) {
        throw error
      }
      missingSegments.unshift(basename(existingAncestor))
      existingAncestor = parent
    }
  }
}

async function filesystemPathIdentity(path: string): Promise<string> {
  return canonicalFilesystemPath(path)
}

async function cleanStagingFiles(
  staged: readonly StagedGeneratedOutput[],
  deletions: readonly StagedGeneratedDeletion[] = []
): Promise<void> {
  await Promise.allSettled(
    [
      ...staged.flatMap((entry) => [entry.stagedPath, entry.backupPath]),
      ...deletions.map((entry) => entry.backupPath),
    ].map((path) => rm(path, { force: true }))
  )
}

async function cleanStagedWrites(staged: readonly StagedGeneratedOutput[]): Promise<void> {
  await Promise.allSettled(staged.map((entry) => rm(entry.stagedPath, { force: true })))
}

async function rollbackGeneratedOutputs(
  installed: readonly StagedGeneratedOutput[],
  backedUp: readonly (StagedGeneratedDeletion | StagedGeneratedOutput)[]
): Promise<unknown[]> {
  const errors: unknown[] = []
  for (const entry of installed.toReversed()) {
    try {
      await rm(entry.outputPath, { force: true })
    } catch (error) {
      errors.push(error)
    }
  }
  for (const entry of backedUp.toReversed()) {
    try {
      await rename(entry.backupPath, entry.outputPath)
    } catch (error) {
      errors.push(error)
    }
  }
  return errors
}

async function commitGeneratedOutputs(
  outputs: readonly GeneratedOutput[],
  stalePaths: readonly string[]
): Promise<void> {
  const outputByPath = new Map<string, GeneratedOutput>()
  for (const output of outputs) {
    const identity = await filesystemPathIdentity(output.outputPath)
    const first = outputByPath.get(identity)
    if (first) {
      throw new Error(
        `Generated output paths ${first.outputPath} and ${output.outputPath} refer to the same filesystem destination, which is claimed more than once.`
      )
    }
    outputByPath.set(identity, output)
  }

  const orderedOutputs = [...outputByPath.values()].toSorted((left, right) =>
    left.outputPath.localeCompare(right.outputPath)
  )
  const staleByPath = new Map<string, string>()
  for (const stalePath of stalePaths) {
    const identity = await filesystemPathIdentity(stalePath)
    if (outputByPath.has(identity)) {
      throw new Error(`Generated output path ${stalePath} cannot be both installed and removed.`)
    }
    if (!staleByPath.has(identity)) {
      staleByPath.set(identity, stalePath)
    }
  }
  const orderedStalePaths = [...staleByPath.values()].toSorted()
  for (const output of orderedOutputs) {
    await assertOutputIsNotSymbolicLink(output.outputPath)
  }
  for (const stalePath of orderedStalePaths) {
    await assertOutputIsNotSymbolicLink(stalePath)
  }

  const staged: StagedGeneratedOutput[] = []
  const stagedByPath = new Map<string, StagedGeneratedOutput>()
  const batchNonce = `${process.pid}-${randomUUID()}`
  const deletions: StagedGeneratedDeletion[] = orderedStalePaths.map((outputPath) => ({
    backupPath: join(dirname(outputPath), `.${basename(outputPath)}.${process.pid}-${randomUUID()}.backup`),
    outputPath,
  }))
  try {
    for (const output of orderedOutputs) {
      const previous = await existingContents(output.outputPath)
      if (previous === output.contents) {
        continue
      }

      await mkdir(dirname(output.outputPath), { recursive: true })
      const stagedPath = join(dirname(output.outputPath), `.${basename(output.outputPath)}.${batchNonce}.staged`)
      const backupPath = join(dirname(output.outputPath), `.${basename(output.outputPath)}.${batchNonce}.backup`)
      try {
        await writeFile(stagedPath, output.contents, { flag: 'wx' })
      } catch (error) {
        if (isAlreadyExistsError(error)) {
          const first = stagedByPath.get(await filesystemPathIdentity(stagedPath))
          if (first) {
            throw new Error(
              `Generated output paths ${first.outputPath} and ${output.outputPath} refer to the same filesystem destination, which is claimed more than once.`
            )
          }
        }
        throw error
      }
      const entry = { ...output, backupPath, existed: previous !== null, stagedPath }
      staged.push(entry)
      stagedByPath.set(await filesystemPathIdentity(stagedPath), entry)
    }
  } catch (error) {
    await cleanStagingFiles(staged, deletions)
    throw error
  }

  const backedUp: (StagedGeneratedDeletion | StagedGeneratedOutput)[] = []
  const installed: StagedGeneratedOutput[] = []
  try {
    for (const entry of deletions) {
      await rename(entry.outputPath, entry.backupPath)
      backedUp.push(entry)
    }
    for (const entry of staged) {
      if (entry.existed) {
        await rename(entry.outputPath, entry.backupPath)
        backedUp.push(entry)
      }
    }
    for (const entry of staged) {
      await rename(entry.stagedPath, entry.outputPath)
      installed.push(entry)
    }
  } catch (error) {
    const rollbackErrors = await rollbackGeneratedOutputs(installed, backedUp)
    await cleanStagedWrites(staged)
    if (rollbackErrors.length > 0) {
      throw new AggregateError(
        [error, ...rollbackErrors],
        'Generated output commit failed and rollback was incomplete.'
      )
    }
    await cleanStagingFiles(staged, deletions)
    throw error
  }

  await cleanStagingFiles(staged, deletions)
}

export interface GenerateTypedSqlResult {
  readonly generatedFiles: readonly string[]
  readonly removedFiles: number
  readonly statementCount: number
}

export async function generateTypedSql(config: PostgresTypedSqlConfig): Promise<GenerateTypedSqlResult> {
  if (generationInProgress) {
    throw new Error('Concurrent generation in one process is not supported.')
  }

  generationInProgress = true
  let database: Awaited<ReturnType<typeof createAnalysisDatabase>> | undefined

  try {
    const resolvedConfig = resolveConfig(config)
    database = await createAnalysisDatabase({
      extensions: resolvedConfig.extensions,
      schemaFiles: resolvedConfig.schemaFiles,
    })
    const catalogContents = await buildCatalogTypes(database, resolvedConfig)
    const rawConfigs = await readTypedSqlConfigs(resolvedConfig)
    assertUniqueTypedSqlNames(rawConfigs)
    const configs = rawConfigs.map((config) => compileTypedSql(config, resolvedConfig.naming.parameterProperties))
    const resolvedConfigs = await resolveTypedSqlWithAnalyzer(configs, database, resolvedConfig)

    const staleFiles = await findStaleGeneratedFiles(resolvedConfigs, resolvedConfig)
    await commitGeneratedOutputs(
      [
        { contents: catalogContents, outputPath: resolvedConfig.typesOutput },
        ...resolvedConfigs.map((entry) => ({
          contents: renderTypedSql(entry, resolvedConfig),
          outputPath: entry.outputPath,
        })),
      ],
      staleFiles
    )
    return {
      generatedFiles: resolvedConfigs.map((entry) => entry.outputPath),
      removedFiles: staleFiles.length,
      statementCount: configs.length,
    }
  } finally {
    try {
      await database?.close()
    } finally {
      generationInProgress = false
    }
  }
}
